-- Biometric Intelligence Feature
-- Integrates HealthKit data for mood-biometric correlations and insights

-- HealthKit sync status and settings
CREATE TABLE IF NOT EXISTS healthkit_connections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

    -- Authorization status
    is_connected BOOLEAN NOT NULL DEFAULT false,
    authorized_types TEXT[] NOT NULL DEFAULT '{}', -- ['sleep', 'hrv', 'steps', 'activity', 'mindful', 'workouts']

    -- Sync metadata
    last_sync_at TIMESTAMPTZ,
    last_sync_status TEXT, -- 'success', 'partial', 'failed'
    sync_error_message TEXT,

    -- User preferences
    sync_frequency_hours INTEGER NOT NULL DEFAULT 6,
    enable_insights BOOLEAN NOT NULL DEFAULT true,
    enable_alerts BOOLEAN NOT NULL DEFAULT true,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT unique_healthkit_user UNIQUE (user_id)
);

-- Daily biometric summaries (aggregated from HealthKit)
CREATE TABLE IF NOT EXISTS biometric_daily_summaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL,

    -- Sleep metrics
    sleep_duration_minutes INTEGER, -- Total sleep
    sleep_quality_score DECIMAL(3,2), -- 0-1 scale
    sleep_start_time TIME,
    sleep_end_time TIME,
    time_in_bed_minutes INTEGER,
    sleep_efficiency DECIMAL(3,2), -- sleep_duration / time_in_bed

    -- HRV metrics
    hrv_average_ms DECIMAL(6,2), -- Milliseconds
    hrv_min_ms DECIMAL(6,2),
    hrv_max_ms DECIMAL(6,2),
    resting_heart_rate INTEGER,

    -- Activity metrics
    steps_count INTEGER,
    active_energy_kcal INTEGER,
    exercise_minutes INTEGER,
    stand_hours INTEGER,
    distance_meters INTEGER,

    -- Mindfulness
    mindful_minutes INTEGER,

    -- Computed scores
    overall_wellness_score DECIMAL(3,2), -- 0-1 composite score

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT unique_daily_summary UNIQUE (user_id, date)
);

-- Workout sessions synced from HealthKit
CREATE TABLE IF NOT EXISTS biometric_workouts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    healthkit_uuid TEXT, -- Original HealthKit UUID for deduplication

    workout_type TEXT NOT NULL, -- 'running', 'walking', 'cycling', 'yoga', etc.
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    duration_minutes INTEGER NOT NULL,

    -- Metrics (optional based on workout type)
    active_energy_kcal INTEGER,
    distance_meters INTEGER,
    average_heart_rate INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT unique_workout UNIQUE (user_id, healthkit_uuid)
);

-- Biometric insights generated by analysis
CREATE TABLE IF NOT EXISTS biometric_insights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

    insight_type TEXT NOT NULL, -- 'sleep_mood_correlation', 'activity_pattern', 'hrv_trend', 'wellness_summary'
    insight_category TEXT NOT NULL, -- 'sleep', 'activity', 'stress', 'general'

    -- Content
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    detail_json JSONB, -- Detailed data for drill-down

    -- Correlation data (if applicable)
    correlation_strength DECIMAL(3,2), -- -1 to 1
    confidence_score DECIMAL(3,2), -- 0 to 1
    data_points_count INTEGER,
    period_start_date DATE,
    period_end_date DATE,

    -- Status
    is_read BOOLEAN NOT NULL DEFAULT false,
    read_at TIMESTAMPTZ,
    is_dismissed BOOLEAN NOT NULL DEFAULT false,

    -- Feedback
    user_rating INTEGER CHECK (user_rating BETWEEN 1 AND 5),
    user_feedback TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ -- Some insights are time-sensitive
);

-- User's personal baselines (computed over time)
CREATE TABLE IF NOT EXISTS biometric_baselines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

    metric_type TEXT NOT NULL, -- 'sleep_duration', 'hrv', 'steps', 'resting_hr'

    -- Baseline values
    baseline_value DECIMAL(10,2) NOT NULL,
    baseline_std_dev DECIMAL(10,2),
    baseline_min DECIMAL(10,2),
    baseline_max DECIMAL(10,2),

    -- Computation metadata
    computed_from_days INTEGER NOT NULL, -- Number of days used
    last_computed_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT unique_baseline UNIQUE (user_id, metric_type)
);

-- Biometric alerts sent to user
CREATE TABLE IF NOT EXISTS biometric_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

    alert_type TEXT NOT NULL, -- 'low_sleep', 'hrv_drop', 'inactivity', 'stress_elevated'
    severity TEXT NOT NULL DEFAULT 'info', -- 'info', 'warning', 'urgent'

    title TEXT NOT NULL,
    message TEXT NOT NULL,

    -- Trigger data
    trigger_metric TEXT NOT NULL,
    trigger_value DECIMAL(10,2),
    baseline_value DECIMAL(10,2),
    deviation_percent DECIMAL(5,2),

    -- Suggested action
    suggested_action_type TEXT, -- 'breathing', 'exercise', 'rest', 'meditation'
    suggested_action_id UUID, -- Reference to exercise if applicable

    -- Status
    is_sent BOOLEAN NOT NULL DEFAULT false,
    sent_at TIMESTAMPTZ,
    is_read BOOLEAN NOT NULL DEFAULT false,
    read_at TIMESTAMPTZ,
    action_taken BOOLEAN,
    action_taken_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Mood-biometric correlation cache (for fast insights)
CREATE TABLE IF NOT EXISTS mood_biometric_correlations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

    biometric_type TEXT NOT NULL, -- 'sleep_duration', 'sleep_quality', 'hrv', 'steps', 'exercise'
    correlation_coefficient DECIMAL(4,3) NOT NULL, -- -1 to 1
    p_value DECIMAL(6,5), -- Statistical significance
    data_points INTEGER NOT NULL,

    period_days INTEGER NOT NULL, -- 7, 30, 90 days
    computed_at TIMESTAMPTZ NOT NULL,

    -- Interpretation
    strength_label TEXT, -- 'strong', 'moderate', 'weak', 'none'
    direction_label TEXT, -- 'positive', 'negative', 'neutral'

    CONSTRAINT unique_correlation UNIQUE (user_id, biometric_type, period_days)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_biometric_daily_user_date ON biometric_daily_summaries(user_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_biometric_insights_user ON biometric_insights(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_biometric_insights_unread ON biometric_insights(user_id) WHERE NOT is_read;
CREATE INDEX IF NOT EXISTS idx_biometric_alerts_user ON biometric_alerts(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_biometric_alerts_pending ON biometric_alerts(user_id) WHERE NOT is_sent;
CREATE INDEX IF NOT EXISTS idx_biometric_workouts_user ON biometric_workouts(user_id, start_time DESC);

-- RLS Policies
ALTER TABLE healthkit_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE biometric_daily_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE biometric_workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE biometric_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE biometric_baselines ENABLE ROW LEVEL SECURITY;
ALTER TABLE biometric_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE mood_biometric_correlations ENABLE ROW LEVEL SECURITY;

-- Users can only access their own biometric data
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own healthkit connection') THEN
        CREATE POLICY "Users manage own healthkit connection"
            ON healthkit_connections FOR ALL
            USING (auth.uid() = user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users read own daily summaries') THEN
        CREATE POLICY "Users read own daily summaries"
            ON biometric_daily_summaries FOR SELECT
            USING (auth.uid() = user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users insert own daily summaries') THEN
        CREATE POLICY "Users insert own daily summaries"
            ON biometric_daily_summaries FOR INSERT
            WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users update own daily summaries') THEN
        CREATE POLICY "Users update own daily summaries"
            ON biometric_daily_summaries FOR UPDATE
            USING (auth.uid() = user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own workouts') THEN
        CREATE POLICY "Users manage own workouts"
            ON biometric_workouts FOR ALL
            USING (auth.uid() = user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users read own insights') THEN
        CREATE POLICY "Users read own insights"
            ON biometric_insights FOR SELECT
            USING (auth.uid() = user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users update own insights') THEN
        CREATE POLICY "Users update own insights"
            ON biometric_insights FOR UPDATE
            USING (auth.uid() = user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users read own baselines') THEN
        CREATE POLICY "Users read own baselines"
            ON biometric_baselines FOR SELECT
            USING (auth.uid() = user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users manage own alerts') THEN
        CREATE POLICY "Users manage own alerts"
            ON biometric_alerts FOR ALL
            USING (auth.uid() = user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users read own correlations') THEN
        CREATE POLICY "Users read own correlations"
            ON mood_biometric_correlations FOR SELECT
            USING (auth.uid() = user_id);
    END IF;
END $$;

-- Service role policies for Edge Functions to insert/update data
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Service role manages insights') THEN
        CREATE POLICY "Service role manages insights"
            ON biometric_insights FOR ALL
            TO service_role
            USING (true);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Service role manages baselines') THEN
        CREATE POLICY "Service role manages baselines"
            ON biometric_baselines FOR ALL
            TO service_role
            USING (true);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Service role manages correlations') THEN
        CREATE POLICY "Service role manages correlations"
            ON mood_biometric_correlations FOR ALL
            TO service_role
            USING (true);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Service role manages alerts') THEN
        CREATE POLICY "Service role manages alerts"
            ON biometric_alerts FOR ALL
            TO service_role
            USING (true);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Service role manages daily summaries') THEN
        CREATE POLICY "Service role manages daily summaries"
            ON biometric_daily_summaries FOR ALL
            TO service_role
            USING (true);
    END IF;
END $$;
