-- Default challenges seeding
-- Note: created_by references system user that may not exist in all environments
-- These can be created manually via admin dashboard or seed script when system user is provisioned

-- INSERT INTO challenges (name, description, created_by, circle_id, category, duration_days, starts_at, ends_at, rules_json, reward_badge_id, max_participants)
-- VALUES
--     (
--         'Seven Day Streak Challenge',
--         'Complete your daily quest for 7 consecutive days',
--         (SELECT id FROM auth.users WHERE email = 'system@mindfriend.app' LIMIT 1),
--         NULL,
--         'personal',
--         7,
--         NOW(),
--         NOW() + INTERVAL '7 days',
--         '{"required_daily_quests": 7}',
--         NULL,
--         NULL
--     ),
--     (
--         'Mindful Minutes',
--         'Complete 30 minutes of mindfulness exercises',
--         (SELECT id FROM auth.users WHERE email = 'system@mindfriend.app' LIMIT 1),
--         NULL,
--         'personal',
--         7,
--         NOW(),
--         NOW() + INTERVAL '7 days',
--         '{"required_exercise_minutes": 30, "exercise_types": ["meditation"]}',
--         NULL,
--         NULL
--     ),
--     (
--         'Quest Master',
--         'Complete 20 quests in a week',
--         (SELECT id FROM auth.users WHERE email = 'system@mindfriend.app' LIMIT 1),
--         NULL,
--         'personal',
--         7,
--         NOW(),
--         NOW() + INTERVAL '7 days',
--         '{"required_quests": 20}',
--         NULL,
--         NULL
--     ),
--     (
--         'Mood Awareness Week',
--         'Log your mood every day for a week',
--         (SELECT id FROM auth.users WHERE email = 'system@mindfriend.app' LIMIT 1),
--         NULL,
--         'personal',
--         7,
--         NOW(),
--         NOW() + INTERVAL '7 days',
--         '{"required_daily_moods": 7}',
--         NULL,
--         NULL
--     ),
--     (
--         'Breathe Easy',
--         'Complete 10 breathing exercises',
--         (SELECT id FROM auth.users WHERE email = 'system@mindfriend.app' LIMIT 1),
--         NULL,
--         'personal',
--         14,
--         NOW(),
--         NOW() + INTERVAL '14 days',
--         '{"required_breathing_exercises": 10}',
--         NULL,
--         NULL
--     );
