-- ================================================
-- Migration: Seed Conversation Rehearsal Scenarios
-- Created: 2026-01-20
-- Description: Insert 21 pre-built scenarios across 6 categories
-- ================================================

INSERT INTO conversation_scenarios (
    category, title, description, situation_context, other_party_role, other_party_personality,
    key_points_to_convey, desired_outcome, difficulty_level, estimated_minutes, tips_for_user, tags, is_premium
) VALUES
-- Work scenarios (7)
('work', 'Ask for a Raise', 'Request salary increase based on performance',
 'Your annual review is coming up, and you''ve exceeded all your targets this year. You want to request a 15% raise based on your performance and market research.',
 'manager', 'professional and evaluative',
 ARRAY['Performance achievements', 'Market rate research', 'Specific raise amount'],
 'Secure 15% raise or clear timeline for next review',
 'medium', 10,
 ARRAY['Bring specific data and examples', 'Stay confident and professional', 'Be prepared for negotiation'],
 ARRAY['compensation', 'negotiation', 'career'], false),

('work', 'Request Time Off', 'Ask for vacation during busy period',
 'You need to request two weeks off for a family event, but it''s during a typically busy time at work.',
 'manager', 'busy and slightly stressed',
 ARRAY['Why time off is important', 'How work will be covered', 'Flexible on dates if needed'],
 'Get approval for time off with coverage plan',
 'easy', 5,
 ARRAY['Offer solutions for coverage', 'Be respectful of business needs', 'Provide advance notice'],
 ARRAY['boundaries', 'planning'], false),

('work', 'Address Workload Concerns', 'Discuss unsustainable workload with manager',
 'You''ve been working 60+ hour weeks for 3 months and it''s affecting your health. You need to address this with your manager.',
 'manager', 'demanding but reasonable',
 ARRAY['Current workload impact', 'Specific examples', 'Request for prioritization'],
 'Reduce hours to sustainable level or get additional support',
 'medium', 10,
 ARRAY['Document specific examples', 'Focus on solutions', 'Be honest about impact'],
 ARRAY['boundaries', 'burnout', 'self-care'], false),

('work', 'Negotiate Job Offer', 'Negotiate salary and benefits for new position',
 'You received a job offer, but the salary is 10% lower than expected. You want to negotiate before accepting.',
 'hiring manager', 'eager but constrained by budget',
 ARRAY['Market value justification', 'Your unique qualifications', 'Alternative benefits if salary fixed'],
 'Increase offer by 10% or add benefits worth equivalent',
 'advanced', 15,
 ARRAY['Research market rates thoroughly', 'Express enthusiasm for role', 'Be willing to walk away'],
 ARRAY['negotiation', 'career', 'compensation'], true),

('work', 'Quit Job Professionally', 'Resign while maintaining positive relationship',
 'You''ve accepted a new job and need to resign. You want to leave on good terms.',
 'manager', 'surprised and disappointed',
 ARRAY['Gratitude for opportunities', 'Professional reasons for leaving', 'Transition plan'],
 'Resign gracefully with 2-week notice and smooth handoff',
 'medium', 10,
 ARRAY['Be appreciative not apologetic', 'Don''t over-explain', 'Offer to help with transition'],
 ARRAY['career', 'transitions'], false),

('work', 'Give Difficult Feedback to Peer', 'Address colleague''s behavior professionally',
 'A coworker consistently misses deadlines, affecting your work. You need to address this directly.',
 'coworker', 'defensive and stressed',
 ARRAY['Specific examples of impact', 'Your needs', 'Collaborative solution'],
 'Agreement on improved communication and deadlines',
 'medium', 10,
 ARRAY['Use "I" statements', 'Focus on impact not blame', 'Suggest solutions'],
 ARRAY['feedback', 'collaboration'], false),

('work', 'Handle Micromanagement', 'Set boundaries with overly involved manager',
 'Your manager checks in every hour and questions all your decisions. It''s undermining your confidence.',
 'manager', 'anxious and controlling',
 ARRAY['Request for autonomy', 'Your track record', 'Proposed check-in schedule'],
 'Establish clear boundaries and trust-based check-ins',
 'advanced', 15,
 ARRAY['Stay calm and professional', 'Acknowledge their concerns', 'Propose structured alternative'],
 ARRAY['boundaries', 'autonomy', 'trust'], true),

-- Relationship scenarios (5)
('relationships', 'Break Bad News to Partner', 'Share difficult information with romantic partner',
 'You need to tell your partner that you lost your job. You''re worried about their reaction.',
 'romantic partner', 'supportive but concerned',
 ARRAY['What happened', 'Your plan forward', 'How they can support you'],
 'Share news honestly and feel supported',
 'advanced', 15,
 ARRAY['Be honest and direct', 'Show you have a plan', 'Ask for specific support'],
 ARRAY['vulnerability', 'support', 'honesty'], false),

('relationships', 'Have "The Talk" About Relationship', 'Discuss relationship future and commitment',
 'You''ve been dating for a year and want to discuss where things are going.',
 'romantic partner', 'cautious but caring',
 ARRAY['What you want', 'Understanding their perspective', 'Timeline discussion'],
 'Clear mutual understanding of relationship direction',
 'advanced', 15,
 ARRAY['Be clear about your needs', 'Listen actively', 'Avoid ultimatums'],
 ARRAY['commitment', 'communication', 'future'], true),

('relationships', 'Address Trust Issues', 'Discuss concerns about honesty in relationship',
 'You''ve noticed your partner has been secretive about their phone. You need to address your concerns.',
 'romantic partner', 'defensive and hurt',
 ARRAY['Specific observations', 'Your feelings', 'Request for transparency'],
 'Restore trust through open communication',
 'medium', 10,
 ARRAY['Use "I feel" statements', 'Avoid accusations', 'Be open to their perspective'],
 ARRAY['trust', 'communication', 'vulnerability'], false),

('relationships', 'Ask for Space', 'Request temporary distance in relationship',
 'You''re feeling overwhelmed and need some time alone to process things.',
 'romantic partner', 'confused and worried',
 ARRAY['Why you need space', 'It''s not about them', 'What space looks like'],
 'Get space while reassuring partner',
 'easy', 5,
 ARRAY['Be clear it''s temporary', 'Reassure them', 'Define what space means'],
 ARRAY['boundaries', 'self-care'], false),

('relationships', 'Apologize Sincerely', 'Make amends after hurting partner',
 'You said something hurtful during an argument. You want to apologize genuinely.',
 'romantic partner', 'hurt and distant',
 ARRAY['Acknowledge harm', 'Take responsibility', 'Plan to change'],
 'Rebuild trust through sincere apology',
 'medium', 10,
 ARRAY['No "but" statements', 'Listen to their hurt', 'Show changed behavior'],
 ARRAY['accountability', 'repair', 'growth'], false),

-- Social scenarios (4)
('social', 'Navigate Group Conflict', 'Address tension within friend group',
 'Two friends in your group are fighting and putting others in the middle. You want to address it.',
 'friend group', 'divided and tense',
 ARRAY['Acknowledge discomfort', 'Set boundaries', 'Encourage direct communication'],
 'Establish boundary that you won''t take sides',
 'medium', 10,
 ARRAY['Stay neutral', 'Encourage direct resolution', 'Set clear boundaries'],
 ARRAY['boundaries', 'friendships', 'conflict'], false),

('social', 'Decline Invitation Gracefully', 'Say no to social event without guilt',
 'A friend invited you to their party, but you''re exhausted and need downtime.',
 'friend', 'enthusiastic and persuasive',
 ARRAY['Gratitude for invite', 'Honest but brief reason', 'Alternative suggestion'],
 'Decline invitation while maintaining friendship',
 'easy', 5,
 ARRAY['Be warm but firm', 'Don''t over-explain', 'Suggest alternative time'],
 ARRAY['boundaries', 'self-care'], false),

('social', 'Address Uncomfortable Joke', 'Call out inappropriate humor from friend',
 'A friend made a joke that crossed a line. You want to address it without ruining the friendship.',
 'friend', 'joking and unaware',
 ARRAY['Why joke was hurtful', 'Your boundary', 'Request for change'],
 'Set boundary while preserving friendship',
 'medium', 10,
 ARRAY['Be direct but kind', 'Explain impact', 'Assume good intent'],
 ARRAY['boundaries', 'values', 'communication'], false),

('social', 'Make New Friends at Event', 'Start conversations with strangers',
 'You''re at a networking event and want to make meaningful connections.',
 'stranger at event', 'friendly but busy',
 ARRAY['Genuine introduction', 'Find common ground', 'Exchange contact info'],
 'Make 2-3 genuine connections',
 'easy', 5,
 ARRAY['Ask open-ended questions', 'Show genuine interest', 'Be yourself'],
 ARRAY['networking', 'social-skills', 'connections'], false),

-- Family scenarios (3)
('family', 'Set Boundaries with Parent', 'Address parent''s overstepping behavior',
 'Your parent frequently gives unsolicited advice and criticizes your choices. You need to set a boundary.',
 'parent', 'well-meaning but intrusive',
 ARRAY['Specific behavior to change', 'Why it''s hurtful', 'Consequence if continues'],
 'Establish respectful boundary',
 'medium', 10,
 ARRAY['Be respectful but firm', 'Acknowledge their care', 'State clear boundary'],
 ARRAY['boundaries', 'family-dynamics', 'respect'], false),

('family', 'Discuss Sensitive Topic with Sibling', 'Address family issue with brother/sister',
 'You need to talk to your sibling about caring for aging parents. It''s a sensitive topic.',
 'sibling', 'avoidant and stressed',
 ARRAY['Shared responsibility', 'Your concerns', 'Proposed plan'],
 'Create plan for parent care together',
 'medium', 10,
 ARRAY['Start with empathy', 'Share the burden', 'Be solution-focused'],
 ARRAY['family-caregiving', 'responsibility', 'collaboration'], false),

('family', 'Ask for Help from Family', 'Request support during difficult time',
 'You''re struggling financially and need to ask family for temporary help.',
 'family member', 'caring but potentially judgmental',
 ARRAY['Situation explanation', 'Specific request', 'Repayment plan'],
 'Get support without damaging pride',
 'easy', 5,
 ARRAY['Be specific about needs', 'Show you have a plan', 'Express gratitude'],
 ARRAY['vulnerability', 'support', 'financial'], false),

-- Health scenario (1)
('health', 'Discuss Symptoms with Doctor', 'Advocate for yourself in medical appointment',
 'You''ve been experiencing symptoms your doctor dismissed last time. You need to be more assertive.',
 'doctor', 'rushed and clinical',
 ARRAY['All symptoms clearly', 'Impact on daily life', 'Request for tests/referral'],
 'Be heard and get proper investigation',
 'medium', 10,
 ARRAY['Write symptoms down beforehand', 'Be specific about impact', 'Ask questions'],
 ARRAY['self-advocacy', 'health', 'assertiveness'], false),

-- Financial scenario (1)
('financial', 'Discuss Finances with Partner', 'Have difficult money conversation',
 'You and your partner need to discuss differing spending habits that are causing tension.',
 'romantic partner', 'defensive about spending',
 ARRAY['Financial goals alignment', 'Specific concerns', 'Budget proposal'],
 'Create shared financial plan',
 'advanced', 15,
 ARRAY['Focus on shared goals', 'Avoid blame', 'Be willing to compromise'],
 ARRAY['money', 'partnership', 'planning'], true)

ON CONFLICT DO NOTHING;
