#!/usr/bin/env python3
"""
Translate all missing strings in Localizable.xcstrings to Spanish and Portuguese-Brazil.
"""
import json
import re

# Comprehensive translation dictionary
TRANSLATIONS = {
    # Special characters and symbols
    "''": {"es": "''", "pt-BR": "''"},
    "\"": {"es": "\"", "pt-BR": "\""},
    "'": {"es": "'", "pt-BR": "'"},
    "•": {"es": "•", "pt-BR": "•"},
    
    # Format strings - keep placeholders intact
    "%.1fx": {"es": "%.1fx", "pt-BR": "%.1fx"},
    "%@": {"es": "%@", "pt-BR": "%@"},
    "%@ category": {"es": "Categoría %@", "pt-BR": "Categoria %@"},
    "%@ step. %@. %lld of %lld items identified.": {"es": "Paso %@. %@. %lld de %lld elementos identificados.", "pt-BR": "Passo %@. %@. %lld de %lld itens identificados."},
    "%@ theme%@": {"es": "Tema %@%@", "pt-BR": "Tema %@%@"},
    "%@ trend over %lld days": {"es": "Tendencia %@ en %lld días", "pt-BR": "Tendência %@ em %lld dias"},
    "%@ • %@": {"es": "%@ • %@", "pt-BR": "%@ • %@"},
    "%@%@ pts/day": {"es": "%@%@ pts/día", "pt-BR": "%@%@ pts/dia"},
    "%@%lld": {"es": "%@%lld", "pt-BR": "%@%lld"},
    "%@%lld from yesterday": {"es": "%@%lld desde ayer", "pt-BR": "%@%lld desde ontem"},
    "%@%lld%% HRV change": {"es": "%@%lld%% cambio en VFC", "pt-BR": "%@%lld%% mudança na VFC"},
    "%@'s profile picture": {"es": "Foto de perfil de %@", "pt-BR": "Foto de perfil de %@"},
    "%@. %@. Impact: %@": {"es": "%@. %@. Impacto: %@", "pt-BR": "%@. %@. Impacto: %@"},
    "%@. Day %lld, %@. %lld percent complete.": {"es": "%@. Día %lld, %@. %lld por ciento completado.", "pt-BR": "%@. Dia %lld, %@. %lld porcento completo."},
    "%@. Impact: %@": {"es": "%@. Impacto: %@", "pt-BR": "%@. Impacto: %@"},
    
    # Number formats
    "%lld AI profile picture generations remaining today": {"es": "%lld generaciones de foto de perfil con IA restantes hoy", "pt-BR": "%lld gerações de foto de perfil com IA restantes hoje"},
    "%lld BPM": {"es": "%lld PPM", "pt-BR": "%lld BPM"},
    "%lld XP to next": {"es": "%lld XP para el siguiente", "pt-BR": "%lld XP para o próximo"},
    "%lld avg": {"es": "%lld promedio", "pt-BR": "%lld média"},
    "%lld cards": {"es": "%lld tarjetas", "pt-BR": "%lld cartões"},
    "%lld characters entered": {"es": "%lld caracteres ingresados", "pt-BR": "%lld caracteres inseridos"},
    "%lld chat messages remaining": {"es": "%lld mensajes de chat restantes", "pt-BR": "%lld mensagens de chat restantes"},
    "%lld excluded": {"es": "%lld excluidos", "pt-BR": "%lld excluídos"},
    "%lld left": {"es": "%lld restantes", "pt-BR": "%lld restantes"},
    "%lld mentors": {"es": "%lld mentores", "pt-BR": "%lld mentores"},
    "%lld min before": {"es": "%lld min antes", "pt-BR": "%lld min antes"},
    "%lld min • %@": {"es": "%lld min • %@", "pt-BR": "%lld min • %@"},
    "%lld ms": {"es": "%lld ms", "pt-BR": "%lld ms"},
    "%lld objects": {"es": "%lld objetos", "pt-BR": "%lld objetos"},
    "%lld objects placed": {"es": "%lld objetos colocados", "pt-BR": "%lld objetos colocados"},
    "%lld of %lld chat messages remaining": {"es": "%lld de %lld mensajes de chat restantes", "pt-BR": "%lld de %lld mensagens de chat restantes"},
    "%lld of %lld generations remaining today": {"es": "%lld de %lld generaciones restantes hoy", "pt-BR": "%lld de %lld gerações restantes hoje"},
    "%lld of %lld items identified": {"es": "%lld de %lld elementos identificados", "pt-BR": "%lld de %lld itens identificados"},
    "%lld of 200 characters": {"es": "%lld de 200 caracteres", "pt-BR": "%lld de 200 caracteres"},
    "%lld patterns available": {"es": "%lld patrones disponibles", "pt-BR": "%lld padrões disponíveis"},
    "%lld patterns detected so far": {"es": "%lld patrones detectados hasta ahora", "pt-BR": "%lld padrões detectados até agora"},
    "%lld patterns selected": {"es": "%lld patrones seleccionados", "pt-BR": "%lld padrões selecionados"},
    "%lld percent confidence, %@": {"es": "%lld por ciento de confianza, %@", "pt-BR": "%lld porcento de confiança, %@"},
    "%lld practices": {"es": "%lld prácticas", "pt-BR": "%lld práticas"},
    "%lld pts": {"es": "%lld pts", "pt-BR": "%lld pts"},
    "%lld samples": {"es": "%lld muestras", "pt-BR": "%lld amostras"},
    "%lld supporters": {"es": "%lld apoyo", "pt-BR": "%lld apoiadores"},
    "%lld things you %@": {"es": "%lld cosas que %@", "pt-BR": "%lld coisas que você %@"},
    "%lld weeks": {"es": "%lld semanas", "pt-BR": "%lld semanas"},
    "%lld%% active": {"es": "%lld%% activo", "pt-BR": "%lld%% ativo"},
    "%lld%% confidence": {"es": "%lld%% confianza", "pt-BR": "%lld%% confiança"},
    "%lld%% helpful": {"es": "%lld%% útil", "pt-BR": "%lld%% útil"},
    "%lld%% weight": {"es": "%lld%% peso", "pt-BR": "%lld%% peso"},
    "%lld+": {"es": "%lld+", "pt-BR": "%lld+"},
    "%lld.": {"es": "%lld.", "pt-BR": "%lld."},
    "%lld/%lld Activities": {"es": "%lld/%lld Actividades", "pt-BR": "%lld/%lld Atividades"},
    "%lld/%lld generations used this month": {"es": "%lld/%lld generaciones usadas este mes", "pt-BR": "%lld/%lld gerações usadas este mês"},
    "%lldd": {"es": "%lldd", "pt-BR": "%lldd"},
    "%lldh/week": {"es": "%lldh/semana", "pt-BR": "%lldh/semana"},
    "%lld×": {"es": "%lld×", "pt-BR": "%lld×"},
    "+%@ pts": {"es": "+%@ pts", "pt-BR": "+%@ pts"},
    "+%lld points": {"es": "+%lld puntos", "pt-BR": "+%lld pontos"},
    "+%lld pts": {"es": "+%lld pts", "pt-BR": "+%lld pts"},
    "/ %lld": {"es": "/ %lld", "pt-BR": "/ %lld"},
    "/ 10": {"es": "/ 10", "pt-BR": "/ 10"},
    "/month": {"es": "/mes", "pt-BR": "/mês"},
    "/year": {"es": "/año", "pt-BR": "/ano"},
    " alternatives": {"es": " alternativas", "pt-BR": " alternativas"},
    
    # Time-related
    "12-Month Mood Trend": {"es": "Tendencia de ánimo de 12 meses", "pt-BR": "Tendência de humor de 12 meses"},
    "14-Day Debt Score": {"es": "Puntuación de deuda de 14 días", "pt-BR": "Pontuação de dívida de 14 dias"},
    "24 hours": {"es": "24 horas", "pt-BR": "24 horas"},
    "48 hours": {"es": "48 horas", "pt-BR": "48 horas"},
    "7-Day Recovery Plan": {"es": "Plan de recuperación de 7 días", "pt-BR": "Plano de recuperação de 7 dias"},
    "7-Day Trend": {"es": "Tendencia de 7 días", "pt-BR": "Tendência de 7 dias"},
    "7-day projection: %lld": {"es": "Proyección a 7 días: %lld", "pt-BR": "Projeção de 7 dias: %lld"},
    
    # AR Features
    "A personalized wind-down routine helps you relax and prepare for restful sleep": {"es": "Una rutina personalizada de relajación te ayuda a prepararte para un sueño reparador", "pt-BR": "Uma rotina personalizada de relaxamento ajuda você a se preparar para um sono reparador"},
    "AI Wellness": {"es": "Bienestar con IA", "pt-BR": "Bem-estar com IA"},
    "AR Capabilities": {"es": "Capacidades de RA", "pt-BR": "Capacidades de RA"},
    "AR Not Available": {"es": "RA no disponible", "pt-BR": "RA não disponível"},
    "AR Ready": {"es": "RA listo", "pt-BR": "RA pronto"},
    "AR grounding exercises will appear here when available.": {"es": "Los ejercicios de conexión a tierra con RA aparecerán aquí cuando estén disponibles.", "pt-BR": "Os exercícios de aterramento com RA aparecerão aqui quando disponíveis."},
    "AR tracking status: %@": {"es": "Estado de seguimiento RA: %@", "pt-BR": "Status de rastreamento RA: %@"},
    "AR tracking: %@": {"es": "Seguimiento RA: %@", "pt-BR": "Rastreamento RA: %@"},
    "AUTO": {"es": "AUTO", "pt-BR": "AUTO"},
    
    # About sections
    "About Difficulty Levels": {"es": "Acerca de los niveles de dificultad", "pt-BR": "Sobre os níveis de dificuldade"},
    "About You": {"es": "Acerca de ti", "pt-BR": "Sobre você"},
    "About Your Transition": {"es": "Acerca de tu transición", "pt-BR": "Sobre sua transição"},
    "About this Assessment": {"es": "Acerca de esta evaluación", "pt-BR": "Sobre esta avaliação"},
    
    # Accept/Actions
    "Accept Mentorship": {"es": "Aceptar mentoría", "pt-BR": "Aceitar mentoria"},
    "Accept Request": {"es": "Aceptar solicitud", "pt-BR": "Aceitar solicitação"},
    "Action Details": {"es": "Detalles de la acción", "pt-BR": "Detalhes da ação"},
    "Action History": {"es": "Historial de acciones", "pt-BR": "Histórico de ações"},
    "Action Needed": {"es": "Acción necesaria", "pt-BR": "Ação necessária"},
    "Actions Today": {"es": "Acciones de hoy", "pt-BR": "Ações de hoje"},
    "Activate Vacation Mode": {"es": "Activar modo vacaciones", "pt-BR": "Ativar modo férias"},
    "Activating...": {"es": "Activando...", "pt-BR": "Ativando..."},
    "Active Days": {"es": "Días activos", "pt-BR": "Dias ativos"},
    "Active Journey": {"es": "Viaje activo", "pt-BR": "Jornada ativa"},
    "Active Mentorships": {"es": "Mentorías activas", "pt-BR": "Mentorias ativas"},
    "Active Signals": {"es": "Señales activas", "pt-BR": "Sinais ativos"},
    "Active Warning Signs": {"es": "Señales de alerta activas", "pt-BR": "Sinais de alerta ativos"},
    "Activities": {"es": "Actividades", "pt-BR": "Atividades"},
    "Activity Heatmap": {"es": "Mapa de calor de actividad", "pt-BR": "Mapa de calor de atividade"},
    "Activity Summary": {"es": "Resumen de actividad", "pt-BR": "Resumo de atividades"},
    "Adapt exercises based on heart rate": {"es": "Adaptar ejercicios según la frecuencia cardíaca", "pt-BR": "Adaptar exercícios com base na frequência cardíaca"},
    "Add": {"es": "Agregar", "pt-BR": "Adicionar"},
    "Add Contact": {"es": "Agregar contacto", "pt-BR": "Adicionar contato"},
    "Add Medication": {"es": "Agregar medicamento", "pt-BR": "Adicionar medicamento"},
    "Add Note": {"es": "Agregar nota", "pt-BR": "Adicionar nota"},
    "Add a Caption": {"es": "Agregar una leyenda", "pt-BR": "Adicionar uma legenda"},
    "Add a caption (optional)": {"es": "Agregar una leyenda (opcional)", "pt-BR": "Adicionar uma legenda (opcional)"},
    "Add item": {"es": "Agregar elemento", "pt-BR": "Adicionar item"},
    "Add language": {"es": "Agregar idioma", "pt-BR": "Adicionar idioma"},
    "Add notes (optional)": {"es": "Agregar notas (opcional)", "pt-BR": "Adicionar notas (opcional)"},
    "Adaptive Breathing": {"es": "Respiración adaptativa", "pt-BR": "Respiração adaptativa"},
    "Agent Learnings": {"es": "Aprendizajes del agente", "pt-BR": "Aprendizados do agente"},
    "Agent Settings": {"es": "Configuración del agente", "pt-BR": "Configurações do agente"},
    "AI Insight": {"es": "Información de IA", "pt-BR": "Insight de IA"},
    "AI Memory": {"es": "Memoria de IA", "pt-BR": "Memória de IA"},
    "AI Preferences": {"es": "Preferencias de IA", "pt-BR": "Preferências de IA"},
    "AI Profile Picture": {"es": "Foto de perfil con IA", "pt-BR": "Foto de perfil com IA"},
    "Alerts": {"es": "Alertas", "pt-BR": "Alertas"},
    "All": {"es": "Todo", "pt-BR": "Todos"},
    "Alternative Perspectives": {"es": "Perspectivas alternativas", "pt-BR": "Perspectivas alternativas"},
    "Ambient Themes": {"es": "Temas ambientales", "pt-BR": "Temas ambientais"},
    "Analyze History": {"es": "Analizar historial", "pt-BR": "Analisar histórico"},
    "Analyzing...": {"es": "Analizando...", "pt-BR": "Analisando..."},
    "App Language": {"es": "Idioma de la app", "pt-BR": "Idioma do app"},
    "App Lock": {"es": "Bloqueo de app", "pt-BR": "Bloqueio de app"},
    "Appearance": {"es": "Apariencia", "pt-BR": "Aparência"},
    "Assessments Due": {"es": "Evaluaciones pendientes", "pt-BR": "Avaliações pendentes"},
    "Assessment Results": {"es": "Resultados de la evaluación", "pt-BR": "Resultados da avaliação"},
    "At current pace, you may experience a crash in %lld days.": {"es": "Al ritmo actual, podrías experimentar un colapso en %lld días.", "pt-BR": "No ritmo atual, você pode experimentar um colapso em %lld dias."},
    "Audio": {"es": "Audio", "pt-BR": "Áudio"},
    "Audio Soundscapes": {"es": "Paisajes sonoros", "pt-BR": "Paisagens sonoras"},
    "Autonomy Level": {"es": "Nivel de autonomía", "pt-BR": "Nível de autonomia"},
    "Availability": {"es": "Disponibilidad", "pt-BR": "Disponibilidade"},
    "Available as mentor": {"es": "Disponible como mentor", "pt-BR": "Disponível como mentor"},
    "avg mood": {"es": "ánimo promedio", "pt-BR": "humor médio"},
    
    # B
    "Background Sounds": {"es": "Sonidos de fondo", "pt-BR": "Sons de fundo"},
    "Badges": {"es": "Insignias", "pt-BR": "Medalhas"},
    "Become a Mentor": {"es": "Convertirse en mentor", "pt-BR": "Tornar-se mentor"},
    "Become a Therapist/Coach": {"es": "Convertirse en terapeuta/coach", "pt-BR": "Tornar-se terapeuta/coach"},
    "Biofeedback Settings": {"es": "Configuración de biofeedback", "pt-BR": "Configurações de biofeedback"},
    "Breathwork": {"es": "Respiración", "pt-BR": "Respiração"},
    "Briefing": {"es": "Resumen", "pt-BR": "Resumo"},
    
    # C
    "Calendar (Next 24h)": {"es": "Calendario (próximas 24h)", "pt-BR": "Calendário (próximas 24h)"},
    "Cancel": {"es": "Cancelar", "pt-BR": "Cancelar"},
    "Cancelled": {"es": "Cancelado", "pt-BR": "Cancelado"},
    "Category Analysis": {"es": "Análisis de categoría", "pt-BR": "Análise de categoria"},
    "Certificates": {"es": "Certificados", "pt-BR": "Certificados"},
    "Challenge title": {"es": "Título del desafío", "pt-BR": "Título do desafio"},
    "Check In": {"es": "Registrar", "pt-BR": "Fazer check-in"},
    "Check back tomorrow for a new quest!": {"es": "¡Vuelve mañana para una nueva misión!", "pt-BR": "Volte amanhã para uma nova missão!"},
    "Choose which patterns the agent should monitor.": {"es": "Elige qué patrones debe monitorear el agente.", "pt-BR": "Escolha quais padrões o agente deve monitorar."},
    "Circle name": {"es": "Nombre del círculo", "pt-BR": "Nome do círculo"},
    "Circles": {"es": "Círculos", "pt-BR": "Círculos"},
    "Clear All Memories": {"es": "Borrar todos los recuerdos", "pt-BR": "Limpar todas as memórias"},
    "Clear Filter": {"es": "Limpiar filtro", "pt-BR": "Limpar filtro"},
    "Close": {"es": "Cerrar", "pt-BR": "Fechar"},
    "Coach error: %@": {"es": "Error del coach: %@", "pt-BR": "Erro do coach: %@"},
    "Community Strategies": {"es": "Estrategias de la comunidad", "pt-BR": "Estratégias da comunidade"},
    "Community Wisdom": {"es": "Sabiduría de la comunidad", "pt-BR": "Sabedoria da comunidade"},
    "Community Wisdom Privacy": {"es": "Privacidad de la sabiduría comunitaria", "pt-BR": "Privacidade da sabedoria comunitária"},
    "Complete": {"es": "Completar", "pt-BR": "Completar"},
    "Complete Quest": {"es": "Completar misión", "pt-BR": "Completar missão"},
    "Complete to celebrate your progress": {"es": "Completa para celebrar tu progreso", "pt-BR": "Complete para celebrar seu progresso"},
    "Completed": {"es": "Completado", "pt-BR": "Completado"},
    "Confidence: %lld%%": {"es": "Confianza: %lld%%", "pt-BR": "Confiança: %lld%%"},
    "Contact Name": {"es": "Nombre del contacto", "pt-BR": "Nome do contato"},
    "Contact Sales": {"es": "Contactar ventas", "pt-BR": "Contatar vendas"},
    "Contact Support": {"es": "Contactar soporte", "pt-BR": "Contatar suporte"},
    "Continue": {"es": "Continuar", "pt-BR": "Continuar"},
    "Continue with Google": {"es": "Continuar con Google", "pt-BR": "Continuar com Google"},
    "Continue with Email": {"es": "Continuar con email", "pt-BR": "Continuar com email"},
    "Coping Strategies": {"es": "Estrategias de afrontamiento", "pt-BR": "Estratégias de enfrentamento"},
    "Create": {"es": "Crear", "pt-BR": "Criar"},
    "Create AI Art": {"es": "Crear arte con IA", "pt-BR": "Criar arte com IA"},
    "Create Circle": {"es": "Crear círculo", "pt-BR": "Criar círculo"},
    "Create Content": {"es": "Crear contenido", "pt-BR": "Criar conteúdo"},
    "Create Exercise": {"es": "Crear ejercicio", "pt-BR": "Criar exercício"},
    "Crisis Resources": {"es": "Recursos de crisis", "pt-BR": "Recursos de crise"},
    "Current Phase: %@": {"es": "Fase actual: %@", "pt-BR": "Fase atual: %@"},
    "Current phase: %@": {"es": "Fase actual: %@", "pt-BR": "Fase atual: %@"},
    "Cycle %lld of %lld": {"es": "Ciclo %lld de %lld", "pt-BR": "Ciclo %lld de %lld"},
    
    # D
    "Daily Briefing": {"es": "Resumen diario", "pt-BR": "Resumo diário"},
    "Data Preview": {"es": "Vista previa de datos", "pt-BR": "Visualização de dados"},
    "Day %lld": {"es": "Día %lld", "pt-BR": "Dia %lld"},
    "Day %lld of %lld": {"es": "Día %lld de %lld", "pt-BR": "Dia %lld de %lld"},
    "Day %lld/%lld": {"es": "Día %lld/%lld", "pt-BR": "Dia %lld/%lld"},
    "Decline": {"es": "Rechazar", "pt-BR": "Recusar"},
    "Delete": {"es": "Eliminar", "pt-BR": "Excluir"},
    "Delete Account": {"es": "Eliminar cuenta", "pt-BR": "Excluir conta"},
    "Delete All Data": {"es": "Eliminar todos los datos", "pt-BR": "Excluir todos os dados"},
    "Delete Entry": {"es": "Eliminar entrada", "pt-BR": "Excluir entrada"},
    "Delete Entry?": {"es": "¿Eliminar entrada?", "pt-BR": "Excluir entrada?"},
    "Delete Prediction Data?": {"es": "¿Eliminar datos de predicción?", "pt-BR": "Excluir dados de previsão?"},
    "Description (optional)": {"es": "Descripción (opcional)", "pt-BR": "Descrição (opcional)"},
    "Details": {"es": "Detalles", "pt-BR": "Detalhes"},
    "Detected Patterns": {"es": "Patrones detectados", "pt-BR": "Padrões detectados"},
    "Difficulty Levels": {"es": "Niveles de dificultad", "pt-BR": "Níveis de dificuldade"},
    "Dismiss error": {"es": "Descartar error", "pt-BR": "Dispensar erro"},
    "Display Name": {"es": "Nombre para mostrar", "pt-BR": "Nome de exibição"},
    "Done": {"es": "Hecho", "pt-BR": "Concluído"},
    "Dosage": {"es": "Dosis", "pt-BR": "Dosagem"},
    "Due today": {"es": "Pendiente hoy", "pt-BR": "Pendente hoje"},
    "Duration": {"es": "Duración", "pt-BR": "Duração"},
    "Duration (days)": {"es": "Duración (días)", "pt-BR": "Duração (dias)"},
    
    # E
    "Edit": {"es": "Editar", "pt-BR": "Editar"},
    "Edit Profile": {"es": "Editar perfil", "pt-BR": "Editar perfil"},
    "Email": {"es": "Correo electrónico", "pt-BR": "Email"},
    "Email address": {"es": "Dirección de correo electrónico", "pt-BR": "Endereço de email"},
    "Emergency Contact": {"es": "Contacto de emergencia", "pt-BR": "Contato de emergência"},
    "Enable Wellness Agent": {"es": "Habilitar agente de bienestar", "pt-BR": "Ativar agente de bem-estar"},
    "End": {"es": "Finalizar", "pt-BR": "Encerrar"},
    "End Exercise?": {"es": "¿Finalizar ejercicio?", "pt-BR": "Encerrar exercício?"},
    "End Mentorship": {"es": "Finalizar mentoría", "pt-BR": "Encerrar mentoria"},
    "End Mentorship?": {"es": "¿Finalizar mentoría?", "pt-BR": "Encerrar mentoria?"},
    "End exercise": {"es": "Finalizar ejercicio", "pt-BR": "Encerrar exercício"},
    "Energy Level: %lld": {"es": "Nivel de energía: %lld", "pt-BR": "Nível de energia: %lld"},
    "Enter promo code": {"es": "Ingresa el código promocional", "pt-BR": "Digite o código promocional"},
    "Enter something you %@": {"es": "Ingresa algo que %@", "pt-BR": "Digite algo que você %@"},
    "Enter your intent...": {"es": "Ingresa tu intención...", "pt-BR": "Digite sua intenção..."},
    "Entry content": {"es": "Contenido de la entrada", "pt-BR": "Conteúdo da entrada"},
    "Entry title": {"es": "Título de la entrada", "pt-BR": "Título da entrada"},
    "Error": {"es": "Error", "pt-BR": "Erro"},
    "Error Loading Data": {"es": "Error al cargar datos", "pt-BR": "Erro ao carregar dados"},
    "Evidence AGAINST the thought": {"es": "Evidencia EN CONTRA del pensamiento", "pt-BR": "Evidência CONTRA o pensamento"},
    "Evidence FOR the thought": {"es": "Evidencia A FAVOR del pensamiento", "pt-BR": "Evidência A FAVOR do pensamento"},
    "Exercise": {"es": "Ejercicio", "pt-BR": "Exercício"},
    "Exercise Type": {"es": "Tipo de ejercicio", "pt-BR": "Tipo de exercício"},
    "Exercises": {"es": "Ejercicios", "pt-BR": "Exercícios"},
    "Exit Current Journey": {"es": "Salir del viaje actual", "pt-BR": "Sair da jornada atual"},
    "Exit Journey": {"es": "Salir del viaje", "pt-BR": "Sair da jornada"},
    "Exit Recovery Mode": {"es": "Salir del modo de recuperación", "pt-BR": "Sair do modo de recuperação"},
    "Expertise Areas": {"es": "Áreas de experiencia", "pt-BR": "Áreas de especialização"},
    "Explore Life Transitions": {"es": "Explorar transiciones de vida", "pt-BR": "Explorar transições de vida"},
    "Export Data": {"es": "Exportar datos", "pt-BR": "Exportar dados"},
    
    # F
    "Family": {"es": "Familia", "pt-BR": "Família"},
    "Family Name": {"es": "Nombre de la familia", "pt-BR": "Nome da família"},
    "Favorites": {"es": "Favoritos", "pt-BR": "Favoritos"},
    "Featured Tonight": {"es": "Destacado esta noche", "pt-BR": "Destaque desta noite"},
    "Filter": {"es": "Filtrar", "pt-BR": "Filtrar"},
    "Find a Mentor": {"es": "Encontrar un mentor", "pt-BR": "Encontrar um mentor"},
    "Flagged": {"es": "Marcado", "pt-BR": "Sinalizado"},
    "For You": {"es": "Para ti", "pt-BR": "Para você"},
    "Forgot Password?": {"es": "¿Olvidaste tu contraseña?", "pt-BR": "Esqueceu a senha?"},
    "From baseline: %lld": {"es": "Desde la línea base: %lld", "pt-BR": "Da linha de base: %lld"},
    "Full Name": {"es": "Nombre completo", "pt-BR": "Nome completo"},
    
    # G
    "Generate Audio": {"es": "Generar audio", "pt-BR": "Gerar áudio"},
    "Generate Exercise": {"es": "Generar ejercicio", "pt-BR": "Gerar exercício"},
    "Generate Exercise for Me": {"es": "Generar ejercicio para mí", "pt-BR": "Gerar exercício para mim"},
    "Generating...": {"es": "Generando...", "pt-BR": "Gerando..."},
    "Generating your insights...": {"es": "Generando tus perspectivas...", "pt-BR": "Gerando seus insights..."},
    "Generating your story...": {"es": "Generando tu historia...", "pt-BR": "Gerando sua história..."},
    "Generation Failed": {"es": "Generación fallida", "pt-BR": "Falha na geração"},
    "Get AI Insights": {"es": "Obtener información de IA", "pt-BR": "Obter insights de IA"},
    "Get crisis help": {"es": "Obtener ayuda de crisis", "pt-BR": "Obter ajuda de crise"},
    "Get started": {"es": "Comenzar", "pt-BR": "Começar"},
    "Give your entry a title...": {"es": "Dale un título a tu entrada...", "pt-BR": "Dê um título à sua entrada..."},
    "Goal: %@ by %@": {"es": "Meta: %@ para %@", "pt-BR": "Meta: %@ até %@"},
    "Great Work!": {"es": "¡Excelente trabajo!", "pt-BR": "Ótimo trabalho!"},
    "Great job completing your quest!": {"es": "¡Excelente trabajo completando tu misión!", "pt-BR": "Ótimo trabalho completando sua missão!"},
    "Guidance for how they can help...": {"es": "Orientación sobre cómo pueden ayudar...", "pt-BR": "Orientação sobre como podem ajudar..."},
    
    # H
    "HTML Preview": {"es": "Vista previa HTML", "pt-BR": "Visualização HTML"},
    "Have an invite code?": {"es": "¿Tienes un código de invitación?", "pt-BR": "Tem um código de convite?"},
    "High: %lld": {"es": "Alto: %lld", "pt-BR": "Alto: %lld"},
    "History": {"es": "Historial", "pt-BR": "Histórico"},
    "Home": {"es": "Inicio", "pt-BR": "Início"},
    "How are you feeling?": {"es": "¿Cómo te sientes?", "pt-BR": "Como você está se sentindo?"},
    "How could we improve?": {"es": "¿Cómo podríamos mejorar?", "pt-BR": "Como podemos melhorar?"},
    "How do you feel after completing this?": {"es": "¿Cómo te sientes después de completar esto?", "pt-BR": "Como você se sente após completar isso?"},
    "How was this %@?": {"es": "¿Cómo estuvo este %@?", "pt-BR": "Como foi este %@?"},
    "How was this quest?": {"es": "¿Cómo estuvo esta misión?", "pt-BR": "Como foi esta missão?"},
    
    # I
    "I'm grateful for...": {"es": "Estoy agradecido por...", "pt-BR": "Sou grato por..."},
    "Insight Lab": {"es": "Laboratorio de perspectivas", "pt-BR": "Laboratório de insights"},
    "Instructions": {"es": "Instrucciones", "pt-BR": "Instruções"},
    "Intervention Settings": {"es": "Configuración de intervención", "pt-BR": "Configurações de intervenção"},
    "Invite Code": {"es": "Código de invitación", "pt-BR": "Código de convite"},
    "Invite Sent!": {"es": "¡Invitación enviada!", "pt-BR": "Convite enviado!"},
    "Invite a Wellness Buddy": {"es": "Invita a un compañero de bienestar", "pt-BR": "Convide um parceiro de bem-estar"},
    
    # J
    "Join": {"es": "Unirse", "pt-BR": "Participar"},
    "Join Circle": {"es": "Unirse al círculo", "pt-BR": "Participar do círculo"},
    
    # K
    "Keep it going!": {"es": "¡Sigue así!", "pt-BR": "Continue assim!"},
    
    # L
    "Language": {"es": "Idioma", "pt-BR": "Idioma"},
    "Later": {"es": "Más tarde", "pt-BR": "Mais tarde"},
    "License Number": {"es": "Número de licencia", "pt-BR": "Número da licença"},
    "Life Events": {"es": "Eventos de vida", "pt-BR": "Eventos de vida"},
    "Listen to nature sounds to relax your mind": {"es": "Escucha sonidos de la naturaleza para relajar tu mente", "pt-BR": "Ouça sons da natureza para relaxar sua mente"},
    "Loading...": {"es": "Cargando...", "pt-BR": "Carregando..."},
    "Loading exercises": {"es": "Cargando ejercicios", "pt-BR": "Carregando exercícios"},
    "Loading today's quest...": {"es": "Cargando la misión de hoy...", "pt-BR": "Carregando a missão de hoje..."},
    "Loading wellbeing data...": {"es": "Cargando datos de bienestar...", "pt-BR": "Carregando dados de bem-estar..."},
    "Loading your briefing...": {"es": "Cargando tu resumen...", "pt-BR": "Carregando seu resumo..."},
    "Location (City, State/Province)": {"es": "Ubicación (Ciudad, Estado/Provincia)", "pt-BR": "Localização (Cidade, Estado/Província)"},
    "Log Life Event": {"es": "Registrar evento de vida", "pt-BR": "Registrar evento de vida"},
    "Log Sleep": {"es": "Registrar sueño", "pt-BR": "Registrar sono"},
    "Log your mood to track your wellness journey": {"es": "Registra tu ánimo para seguir tu viaje de bienestar", "pt-BR": "Registre seu humor para acompanhar sua jornada de bem-estar"},
    "Longest: %lld days": {"es": "Más largo: %lld días", "pt-BR": "Mais longo: %lld dias"},
    "Low: %lld": {"es": "Bajo: %lld", "pt-BR": "Baixo: %lld"},
    
    # M
    "Max %lld actions per day at this level": {"es": "Máximo %lld acciones por día en este nivel", "pt-BR": "Máximo %lld ações por dia neste nível"},
    "Memory Vault": {"es": "Bóveda de recuerdos", "pt-BR": "Cofre de memórias"},
    "Mentorship": {"es": "Mentoría", "pt-BR": "Mentoria"},
    "Mentorship Chat": {"es": "Chat de mentoría", "pt-BR": "Chat de mentoria"},
    "Mentorship Details": {"es": "Detalles de mentoría", "pt-BR": "Detalhes da mentoria"},
    "Message...": {"es": "Mensaje...", "pt-BR": "Mensagem..."},
    "Message input": {"es": "Entrada de mensaje", "pt-BR": "Entrada de mensagem"},
    "Milestone Day!": {"es": "¡Día de hito!", "pt-BR": "Dia de marco!"},
    "Milestone Preview": {"es": "Vista previa del hito", "pt-BR": "Visualização do marco"},
    "Milestone %lld": {"es": "Hito %lld", "pt-BR": "Marco %lld"},
    "Milestone day!": {"es": "¡Día de hito!", "pt-BR": "Dia de marco!"},
    "Milestones": {"es": "Hitos", "pt-BR": "Marcos"},
    "MindFriend is typing": {"es": "MindFriend está escribiendo", "pt-BR": "MindFriend está digitando"},
    "Mix Name": {"es": "Nombre de la mezcla", "pt-BR": "Nome da mixagem"},
    "Monitor your mental health journey": {"es": "Monitorea tu viaje de salud mental", "pt-BR": "Monitore sua jornada de saúde mental"},
    "Mood by Day": {"es": "Ánimo por día", "pt-BR": "Humor por dia"},
    "Mood Check-In": {"es": "Registro de ánimo", "pt-BR": "Check-in de humor"},
    "Mood History": {"es": "Historial de ánimo", "pt-BR": "Histórico de humor"},
    "Mood Prediction": {"es": "Predicción de ánimo", "pt-BR": "Previsão de humor"},
    "Mood: %@": {"es": "Ánimo: %@", "pt-BR": "Humor: %@"},
    "More": {"es": "Más", "pt-BR": "Mais"},
    "My Exercises": {"es": "Mis ejercicios", "pt-BR": "Meus exercícios"},
    "My Matches": {"es": "Mis coincidencias", "pt-BR": "Minhas combinações"},
    "My Mentorships": {"es": "Mis mentorías", "pt-BR": "Minhas mentorias"},
    "My Stories": {"es": "Mis historias", "pt-BR": "Minhas histórias"},
    
    # N
    "Name": {"es": "Nombre", "pt-BR": "Nome"},
    "Name *": {"es": "Nombre *", "pt-BR": "Nome *"},
    "Nature Immersion": {"es": "Inmersión en la naturaleza", "pt-BR": "Imersão na natureza"},
    "Need extra support?": {"es": "¿Necesitas apoyo extra?", "pt-BR": "Precisa de apoio extra?"},
    "Need inspiration?": {"es": "¿Necesitas inspiración?", "pt-BR": "Precisa de inspiração?"},
    "New": {"es": "Nuevo", "pt-BR": "Novo"},
    "New badges earned:": {"es": "Nuevas insignias obtenidas:", "pt-BR": "Novas medalhas conquistadas:"},
    "Next Milestone": {"es": "Próximo hito", "pt-BR": "Próximo marco"},
    "Next milestone in %lld days": {"es": "Próximo hito en %lld días", "pt-BR": "Próximo marco em %lld dias"},
    "No Data Available": {"es": "No hay datos disponibles", "pt-BR": "Nenhum dado disponível"},
    "No Insights Yet": {"es": "Aún no hay perspectivas", "pt-BR": "Nenhum insight ainda"},
    "No Quest Available": {"es": "No hay misión disponible", "pt-BR": "Nenhuma missão disponível"},
    "No actions yet": {"es": "Aún no hay acciones", "pt-BR": "Nenhuma ação ainda"},
    "No briefing available": {"es": "No hay resumen disponible", "pt-BR": "Nenhum resumo disponível"},
    "No %@ available": {"es": "No hay %@ disponible", "pt-BR": "Nenhum %@ disponível"},
    "Not enough mood data yet": {"es": "Aún no hay suficientes datos de ánimo", "pt-BR": "Ainda não há dados de humor suficientes"},
    "Notes...": {"es": "Notas...", "pt-BR": "Notas..."},
    "Notification Channels": {"es": "Canales de notificación", "pt-BR": "Canais de notificação"},
    "Notifications": {"es": "Notificaciones", "pt-BR": "Notificações"},
    
    # O
    "OK": {"es": "OK", "pt-BR": "OK"},
    "One word": {"es": "Una palabra", "pt-BR": "Uma palavra"},
    "Optional feedback": {"es": "Comentarios opcionales", "pt-BR": "Feedback opcional"},
    "Optional feedback...": {"es": "Comentarios opcionales...", "pt-BR": "Feedback opcional..."},
    "Optional notes": {"es": "Notas opcionales", "pt-BR": "Notas opcionais"},
    "Our Approach": {"es": "Nuestro enfoque", "pt-BR": "Nossa abordagem"},
    
    # P
    "Partner Mode": {"es": "Modo de pareja", "pt-BR": "Modo parceiro"},
    "Past Weeks": {"es": "Semanas anteriores", "pt-BR": "Semanas anteriores"},
    "Pattern Alert": {"es": "Alerta de patrón", "pt-BR": "Alerta de padrão"},
    "Patterns Detected": {"es": "Patrones detectados", "pt-BR": "Padrões detectados"},
    "Pause Journey": {"es": "Pausar viaje", "pt-BR": "Pausar jornada"},
    "Paused": {"es": "Pausado", "pt-BR": "Pausado"},
    "Peer Support": {"es": "Apoyo entre pares", "pt-BR": "Apoio entre pares"},
    "Phase Advanced!": {"es": "¡Fase avanzada!", "pt-BR": "Fase avançada!"},
    "Phase Details": {"es": "Detalles de fase", "pt-BR": "Detalhes da fase"},
    "Phase progress: %lld percent": {"es": "Progreso de fase: %lld por ciento", "pt-BR": "Progresso da fase: %lld porcento"},
    "Phone Number": {"es": "Número de teléfono", "pt-BR": "Número de telefone"},
    "Phone number": {"es": "Número de teléfono", "pt-BR": "Número de telefone"},
    "Please sign in to view your insights": {"es": "Por favor inicia sesión para ver tus perspectivas", "pt-BR": "Por favor faça login para ver seus insights"},
    "Please try again after loading your debt status.": {"es": "Por favor intenta de nuevo después de cargar tu estado de deuda.", "pt-BR": "Por favor tente novamente após carregar seu status de dívida."},
    "Portfolio URL": {"es": "URL del portafolio", "pt-BR": "URL do portfólio"},
    "Prediction History": {"es": "Historial de predicciones", "pt-BR": "Histórico de previsões"},
    "Premium": {"es": "Premium", "pt-BR": "Premium"},
    "Preview": {"es": "Vista previa", "pt-BR": "Visualização"},
    "Privacy": {"es": "Privacidad", "pt-BR": "Privacidade"},
    "Privacy Information": {"es": "Información de privacidad", "pt-BR": "Informações de privacidade"},
    "Privacy Policy": {"es": "Política de privacidad", "pt-BR": "Política de privacidade"},
    "Proactive Check-ins": {"es": "Registros proactivos", "pt-BR": "Check-ins proativos"},
    "Profile": {"es": "Perfil", "pt-BR": "Perfil"},
    "Profile Picture": {"es": "Foto de perfil", "pt-BR": "Foto de perfil"},
    "Profile picture": {"es": "Foto de perfil", "pt-BR": "Foto de perfil"},
    "Profile picture placeholder": {"es": "Marcador de foto de perfil", "pt-BR": "Espaço reservado para foto de perfil"},
    "Programs": {"es": "Programas", "pt-BR": "Programas"},
    "Progress Trend": {"es": "Tendencia de progreso", "pt-BR": "Tendência de progresso"},
    "Purpose": {"es": "Propósito", "pt-BR": "Propósito"},
    
    # Q
    "Quest Complete!": {"es": "¡Misión completada!", "pt-BR": "Missão completa!"},
    "Quest Journeys": {"es": "Viajes de misión", "pt-BR": "Jornadas de missão"},
    "Quest completed!": {"es": "¡Misión completada!", "pt-BR": "Missão completa!"},
    "Quick Actions": {"es": "Acciones rápidas", "pt-BR": "Ações rápidas"},
    "Quiet Hours": {"es": "Horas de silencio", "pt-BR": "Horas de silêncio"},
    
    # R
    "Rate Content": {"es": "Calificar contenido", "pt-BR": "Avaliar conteúdo"},
    "Rate Exercise": {"es": "Calificar ejercicio", "pt-BR": "Avaliar exercício"},
    "Rate": {"es": "Tarifa", "pt-BR": "Taxa"},
    "Re-Learn": {"es": "Volver a aprender", "pt-BR": "Reaprender"},
    "Re-Learn Patterns": {"es": "Volver a aprender patrones", "pt-BR": "Reaprender padrões"},
    "Ready for restful sleep?": {"es": "¿Listo para un sueño reparador?", "pt-BR": "Pronto para um sono reparador?"},
    "Recalculate from History": {"es": "Recalcular desde el historial", "pt-BR": "Recalcular a partir do histórico"},
    "Recent Achievements": {"es": "Logros recientes", "pt-BR": "Conquistas recentes"},
    "Recent Actions": {"es": "Acciones recientes", "pt-BR": "Ações recentes"},
    "Recent Results": {"es": "Resultados recientes", "pt-BR": "Resultados recentes"},
    "Recommendations": {"es": "Recomendaciones", "pt-BR": "Recomendações"},
    "Recommended for You": {"es": "Recomendado para ti", "pt-BR": "Recomendado para você"},
    "Recovery Mode": {"es": "Modo de recuperación", "pt-BR": "Modo de recuperação"},
    "Reflection": {"es": "Reflexión", "pt-BR": "Reflexão"},
    "Reflection (optional)": {"es": "Reflexión (opcional)", "pt-BR": "Reflexão (opcional)"},
    "Refresh": {"es": "Actualizar", "pt-BR": "Atualizar"},
    "Remove %@": {"es": "Eliminar %@", "pt-BR": "Remover %@"},
    "Remove profile picture?": {"es": "¿Eliminar foto de perfil?", "pt-BR": "Remover foto de perfil?"},
    "Report Content": {"es": "Reportar contenido", "pt-BR": "Denunciar conteúdo"},
    "Report Safety Concern": {"es": "Reportar preocupación de seguridad", "pt-BR": "Reportar preocupação de segurança"},
    "Request Mentorship": {"es": "Solicitar mentoría", "pt-BR": "Solicitar mentoria"},
    "Reset Password": {"es": "Restablecer contraseña", "pt-BR": "Redefinir senha"},
    "Restart Now": {"es": "Reiniciar ahora", "pt-BR": "Reiniciar agora"},
    "Restart Required": {"es": "Reinicio requerido", "pt-BR": "Reinício necessário"},
    "Restore Purchases": {"es": "Restaurar compras", "pt-BR": "Restaurar compras"},
    "Resume Journey": {"es": "Reanudar viaje", "pt-BR": "Retomar jornada"},
    "Resume within 30 days": {"es": "Reanudar dentro de 30 días", "pt-BR": "Retomar em 30 dias"},
    "Retry": {"es": "Reintentar", "pt-BR": "Tentar novamente"},
    "Rolling Debts": {"es": "Deudas acumuladas", "pt-BR": "Dívidas acumuladas"},
    
    # S
    "SOS History": {"es": "Historial de SOS", "pt-BR": "Histórico de SOS"},
    "SOS Panic Button": {"es": "Botón de pánico SOS", "pt-BR": "Botão de pânico SOS"},
    "SOS Settings": {"es": "Configuración de SOS", "pt-BR": "Configurações de SOS"},
    "Sample Content URL": {"es": "URL de contenido de muestra", "pt-BR": "URL de conteúdo de amostra"},
    "Save": {"es": "Guardar", "pt-BR": "Salvar"},
    "Save & Complete": {"es": "Guardar y completar", "pt-BR": "Salvar e completar"},
    "Save Your Space": {"es": "Guardar tu espacio", "pt-BR": "Salvar seu espaço"},
    "Saved": {"es": "Guardado", "pt-BR": "Salvo"},
    "Scene name": {"es": "Nombre de la escena", "pt-BR": "Nome da cena"},
    "Score: %lld": {"es": "Puntuación: %lld", "pt-BR": "Pontuação: %lld"},
    "Search creators...": {"es": "Buscar creadores...", "pt-BR": "Buscar criadores..."},
    "Search entries": {"es": "Buscar entradas", "pt-BR": "Buscar entradas"},
    "Search tracks": {"es": "Buscar pistas", "pt-BR": "Buscar faixas"},
    "See All": {"es": "Ver todo", "pt-BR": "Ver tudo"},
    "Seeking a mentor": {"es": "Buscando un mentor", "pt-BR": "Buscando um mentor"},
    "Select Calendars": {"es": "Seleccionar calendarios", "pt-BR": "Selecionar calendários"},
    "Send Reset Link": {"es": "Enviar enlace de restablecimiento", "pt-BR": "Enviar link de redefinição"},
    "Send invite": {"es": "Enviar invitación", "pt-BR": "Enviar convite"},
    "Send message": {"es": "Enviar mensaje", "pt-BR": "Enviar mensagem"},
    "Sensory Settings": {"es": "Configuración sensorial", "pt-BR": "Configurações sensoriais"},
    "Sensory Toolkit": {"es": "Kit de herramientas sensoriales", "pt-BR": "Kit de ferramentas sensoriais"},
    "Session Complete": {"es": "Sesión completa", "pt-BR": "Sessão completa"},
    "Session History": {"es": "Historial de sesiones", "pt-BR": "Histórico de sessões"},
    "Session Summary": {"es": "Resumen de sesión", "pt-BR": "Resumo da sessão"},
    "Set Outcome Goal": {"es": "Establecer meta de resultado", "pt-BR": "Definir meta de resultado"},
    "Settings": {"es": "Configuración", "pt-BR": "Configurações"},
    "Setting up your experience, please wait": {"es": "Configurando tu experiencia, por favor espera", "pt-BR": "Configurando sua experiência, por favor aguarde"},
    "Setup Error": {"es": "Error de configuración", "pt-BR": "Erro de configuração"},
    "Severity Level": {"es": "Nivel de gravedad", "pt-BR": "Nível de gravidade"},
    "Share": {"es": "Compartir", "pt-BR": "Compartilhar"},
    "Share Results": {"es": "Compartir resultados", "pt-BR": "Compartilhar resultados"},
    "Share Strategy": {"es": "Compartir estrategia", "pt-BR": "Compartilhar estratégia"},
    "Share more (optional)": {"es": "Compartir más (opcional)", "pt-BR": "Compartilhar mais (opcional)"},
    "Shield History": {"es": "Historial de escudo", "pt-BR": "Histórico de escudo"},
    "Show All Stories": {"es": "Mostrar todas las historias", "pt-BR": "Mostrar todas as histórias"},
    "Show why the agent took each action.": {"es": "Mostrar por qué el agente tomó cada acción.", "pt-BR": "Mostrar por que o agente tomou cada ação."},
    "Sign In Error": {"es": "Error de inicio de sesión", "pt-BR": "Erro de login"},
    "Sign In with Apple": {"es": "Iniciar sesión con Apple", "pt-BR": "Entrar com Apple"},
    "Sign Out": {"es": "Cerrar sesión", "pt-BR": "Sair"},
    "Signal Types": {"es": "Tipos de señal", "pt-BR": "Tipos de sinal"},
    "Skip": {"es": "Omitir", "pt-BR": "Pular"},
    "Skip Sign In (Dev Only)": {"es": "Omitir inicio de sesión (solo desarrollo)", "pt-BR": "Pular login (apenas dev)"},
    "Skip buddy invite": {"es": "Omitir invitación de compañero", "pt-BR": "Pular convite de parceiro"},
    "Skip for now": {"es": "Omitir por ahora", "pt-BR": "Pular por agora"},
    "Skip for today": {"es": "Omitir por hoy", "pt-BR": "Pular por hoje"},
    "Skip personalization": {"es": "Omitir personalización", "pt-BR": "Pular personalização"},
    "Skip to app": {"es": "Ir a la app", "pt-BR": "Ir para o app"},
    "Sleep": {"es": "Sueño", "pt-BR": "Sono"},
    "Sleep Stories": {"es": "Historias para dormir", "pt-BR": "Histórias para dormir"},
    "Smart Interventions": {"es": "Intervenciones inteligentes", "pt-BR": "Intervenções inteligentes"},
    "Social Settings": {"es": "Configuración social", "pt-BR": "Configurações sociais"},
    "Social Vitality": {"es": "Vitalidad social", "pt-BR": "Vitalidade social"},
    "Some content may not be available in all languages. We're always adding more!": {"es": "Algunos contenidos pueden no estar disponibles en todos los idiomas. ¡Siempre estamos agregando más!", "pt-BR": "Alguns conteúdos podem não estar disponíveis em todos os idiomas. Estamos sempre adicionando mais!"},
    "Soundscapes": {"es": "Paisajes sonoros", "pt-BR": "Paisagens sonoras"},
    "Sounds": {"es": "Sonidos", "pt-BR": "Sons"},
    "Start Journey": {"es": "Comenzar viaje", "pt-BR": "Iniciar jornada"},
    "Start Program?": {"es": "¿Iniciar programa?", "pt-BR": "Iniciar programa?"},
    "Start Recovery Program": {"es": "Iniciar programa de recuperación", "pt-BR": "Iniciar programa de recuperação"},
    "Start tracking to see your wellness trends": {"es": "Comienza a rastrear para ver tus tendencias de bienestar", "pt-BR": "Comece a rastrear para ver suas tendências de bem-estar"},
    "Starting %@...": {"es": "Iniciando %@...", "pt-BR": "Iniciando %@..."},
    "Stay in Recovery Mode": {"es": "Permanecer en modo de recuperación", "pt-BR": "Permanecer no modo de recuperação"},
    "Story Preferences": {"es": "Preferencias de historia", "pt-BR": "Preferências de história"},
    "Strategy Submitted": {"es": "Estrategia enviada", "pt-BR": "Estratégia enviada"},
    "Submit": {"es": "Enviar", "pt-BR": "Enviar"},
    "Submit Rating": {"es": "Enviar calificación", "pt-BR": "Enviar avaliação"},
    "Success": {"es": "Éxito", "pt-BR": "Sucesso"},
    "Suggested for you": {"es": "Sugerido para ti", "pt-BR": "Sugerido para você"},
    "Suggestion": {"es": "Sugerencia", "pt-BR": "Sugestão"},
    "Support Resources": {"es": "Recursos de apoyo", "pt-BR": "Recursos de apoio"},
    
    # T
    "Tactile": {"es": "Táctil", "pt-BR": "Tátil"},
    "Tactile Patterns": {"es": "Patrones táctiles", "pt-BR": "Padrões táteis"},
    "Take your first assessment": {"es": "Realiza tu primera evaluación", "pt-BR": "Faça sua primeira avaliação"},
    "Tap for details": {"es": "Toca para detalles", "pt-BR": "Toque para detalhes"},
    "Tap to get started": {"es": "Toca para comenzar", "pt-BR": "Toque para começar"},
    "Tap to view full briefing →": {"es": "Toca para ver el resumen completo →", "pt-BR": "Toque para ver o resumo completo →"},
    "Target Value": {"es": "Valor objetivo", "pt-BR": "Valor alvo"},
    "Template Name": {"es": "Nombre de plantilla", "pt-BR": "Nome do modelo"},
    "Terms of Service": {"es": "Términos de servicio", "pt-BR": "Termos de serviço"},
    "Text": {"es": "Texto", "pt-BR": "Texto"},
    "Thank You": {"es": "Gracias", "pt-BR": "Obrigado"},
    "Thank You!": {"es": "¡Gracias!", "pt-BR": "Obrigado!"},
    "The agent won't send notifications during quiet hours.": {"es": "El agente no enviará notificaciones durante las horas de silencio.", "pt-BR": "O agente não enviará notificações durante as horas de silêncio."},
    "Therapeutic Programs": {"es": "Programas terapéuticos", "pt-BR": "Programas terapêuticos"},
    "Therapist Email": {"es": "Email del terapeuta", "pt-BR": "Email do terapeuta"},
    "Thinking Patterns Identified": {"es": "Patrones de pensamiento identificados", "pt-BR": "Padrões de pensamento identificados"},
    "This Week": {"es": "Esta semana", "pt-BR": "Esta semana"},
    "Thought Record": {"es": "Registro de pensamientos", "pt-BR": "Registro de pensamentos"},
    "Threshold Progress": {"es": "Progreso del umbral", "pt-BR": "Progresso do limite"},
    "Time remaining: %@": {"es": "Tiempo restante: %@", "pt-BR": "Tempo restante: %@"},
    "Timer": {"es": "Temporizador", "pt-BR": "Cronômetro"},
    "Title": {"es": "Título", "pt-BR": "Título"},
    "Title (optional)": {"es": "Título (opcional)", "pt-BR": "Título (opcional)"},
    "To fully apply %@, the app needs to restart. Restart now?": {"es": "Para aplicar completamente %@, la aplicación necesita reiniciarse. ¿Reiniciar ahora?", "pt-BR": "Para aplicar completamente %@, o aplicativo precisa reiniciar. Reiniciar agora?"},
    "Today's Content": {"es": "Contenido de hoy", "pt-BR": "Conteúdo de hoje"},
    "Today's Quest": {"es": "Misión de hoy", "pt-BR": "Missão de hoje"},
    "Today's mood": {"es": "Ánimo de hoy", "pt-BR": "Humor de hoje"},
    "Top Drains Analysis": {"es": "Análisis de principales drenajes", "pt-BR": "Análise dos principais drenos"},
    "Transparency": {"es": "Transparencia", "pt-BR": "Transparência"},
    "Trend: %@": {"es": "Tendencia: %@", "pt-BR": "Tendência: %@"},
    "Try Again": {"es": "Intentar de nuevo", "pt-BR": "Tentar novamente"},
    "Type a message...": {"es": "Escribe un mensaje...", "pt-BR": "Digite uma mensagem..."},
    
    # U
    "Unable to Load": {"es": "No se puede cargar", "pt-BR": "Não foi possível carregar"},
    "Unable to Load Quest": {"es": "No se puede cargar la misión", "pt-BR": "Não foi possível carregar a missão"},
    "Unable to Send": {"es": "No se puede enviar", "pt-BR": "Não foi possível enviar"},
    "Unable to load briefing": {"es": "No se puede cargar el resumen", "pt-BR": "Não foi possível carregar o resumo"},
    "Unable to load debt data": {"es": "No se pueden cargar los datos de deuda", "pt-BR": "Não foi possível carregar os dados de dívida"},
    "Understanding": {"es": "Comprensión", "pt-BR": "Compreensão"},
    "Update": {"es": "Actualizar", "pt-BR": "Atualizar"},
    "Upgrade": {"es": "Mejorar", "pt-BR": "Atualizar"},
    "Use Shield": {"es": "Usar escudo", "pt-BR": "Usar escudo"},
    "Use Streak Shield?": {"es": "¿Usar escudo de racha?", "pt-BR": "Usar escudo de sequência?"},
    
    # V
    "Vacation Mode": {"es": "Modo vacaciones", "pt-BR": "Modo férias"},
    "Vacation Mode Activated": {"es": "Modo vacaciones activado", "pt-BR": "Modo férias ativado"},
    "Velocity: %@ pts/day": {"es": "Velocidad: %@ pts/día", "pt-BR": "Velocidade: %@ pts/dia"},
    "View": {"es": "Ver", "pt-BR": "Ver"},
    "View All": {"es": "Ver todo", "pt-BR": "Ver tudo"},
    "View Full Analysis": {"es": "Ver análisis completo", "pt-BR": "Ver análise completa"},
    "View SOS History": {"es": "Ver historial de SOS", "pt-BR": "Ver histórico de SOS"},
    "View Transaction Breakdown": {"es": "Ver desglose de transacciones", "pt-BR": "Ver detalhamento de transações"},
    "Visual": {"es": "Visual", "pt-BR": "Visual"},
    "Visual Animations": {"es": "Animaciones visuales", "pt-BR": "Animações visuais"},
    "Voice Error": {"es": "Error de voz", "pt-BR": "Erro de voz"},
    "Voice Settings": {"es": "Configuración de voz", "pt-BR": "Configurações de voz"},
    "Voice mode": {"es": "Modo de voz", "pt-BR": "Modo de voz"},
    
    # W
    "Warning Signs": {"es": "Señales de alerta", "pt-BR": "Sinais de alerta"},
    "Warning: Only %lld message%@ left today. Tap to upgrade.": {"es": "Advertencia: Solo quedan %lld mensaje%@ hoy. Toca para mejorar.", "pt-BR": "Aviso: Apenas %lld mensagem%@ restante hoje. Toque para atualizar."},
    "Watch calming animations to focus your attention": {"es": "Mira animaciones relajantes para enfocar tu atención", "pt-BR": "Assista animações relaxantes para focar sua atenção"},
    "Weekly Insights": {"es": "Perspectivas semanales", "pt-BR": "Insights semanais"},
    "Weekly Story": {"es": "Historia semanal", "pt-BR": "História semanal"},
    "Wellbeing Balance": {"es": "Balance de bienestar", "pt-BR": "Equilíbrio de bem-estar"},
    "Wellbeing Debt": {"es": "Deuda de bienestar", "pt-BR": "Dívida de bem-estar"},
    "Wellness Agent": {"es": "Agente de bienestar", "pt-BR": "Agente de bem-estar"},
    "Wellness Predictions": {"es": "Predicciones de bienestar", "pt-BR": "Previsões de bem-estar"},
    "Wellness Tracking": {"es": "Seguimiento de bienestar", "pt-BR": "Rastreamento de bem-estar"},
    "What You'll Experience": {"es": "Lo que experimentarás", "pt-BR": "O que você experimentará"},
    "What are you protecting?": {"es": "¿Qué estás protegiendo?", "pt-BR": "O que você está protegendo?"},
    "What do you %@?": {"es": "¿Qué %@?", "pt-BR": "O que você %@?"},
    "What this means": {"es": "Lo que esto significa", "pt-BR": "O que isso significa"},
    "What's Helping": {"es": "Lo que está ayudando", "pt-BR": "O que está ajudando"},
    "What's on your mind?": {"es": "¿Qué tienes en mente?", "pt-BR": "O que você está pensando?"},
    "What's on your mind? (optional)": {"es": "¿Qué tienes en mente? (opcional)", "pt-BR": "O que você está pensando? (opcional)"},
    "When enabled, the agent will monitor your patterns and send proactive check-ins.": {"es": "Cuando está habilitado, el agente monitoreará tus patrones y enviará registros proactivos.", "pt-BR": "Quando ativado, o agente monitorará seus padrões e enviará check-ins proativos."},
    "When you reach a milestone, you'll see a celebration and can share your achievement with your circles.": {"es": "Cuando alcances un hito, verás una celebración y podrás compartir tu logro con tus círculos.", "pt-BR": "Quando você alcançar um marco, verá uma celebração e poderá compartilhar sua conquista com seus círculos."},
    "Wind-Down Routines": {"es": "Rutinas de relajación", "pt-BR": "Rotinas de relaxamento"},
    "Work Email": {"es": "Email de trabajo", "pt-BR": "Email de trabalho"},
    "Write a review (optional)": {"es": "Escribe una reseña (opcional)", "pt-BR": "Escreva uma avaliação (opcional)"},
    
    # X
    "XP": {"es": "XP", "pt-BR": "XP"},
    
    # Y
    "You have an active journey": {"es": "Tienes un viaje activo", "pt-BR": "Você tem uma jornada ativa"},
    "You'll return to the full home screen with all features.": {"es": "Volverás a la pantalla de inicio completa con todas las funciones.", "pt-BR": "Você retornará à tela inicial completa com todos os recursos."},
    "Your Buddy": {"es": "Tu compañero", "pt-BR": "Seu parceiro"},
    "Your Goals": {"es": "Tus metas", "pt-BR": "Suas metas"},
    "Your Journey": {"es": "Tu viaje", "pt-BR": "Sua jornada"},
    "Your Journeys": {"es": "Tus viajes", "pt-BR": "Suas jornadas"},
    "Your Nickname (optional)": {"es": "Tu apodo (opcional)", "pt-BR": "Seu apelido (opcional)"},
    "Your Privacy": {"es": "Tu privacidad", "pt-BR": "Sua privacidade"},
    "Your Progress": {"es": "Tu progreso", "pt-BR": "Seu progresso"},
    "Your Warning Signs": {"es": "Tus señales de alerta", "pt-BR": "Seus sinais de alerta"},
    "Your agent has learned from %lld interactions": {"es": "Tu agente ha aprendido de %lld interacciones", "pt-BR": "Seu agente aprendeu de %lld interações"},
    "Your personalized insights will appear here every Sunday.": {"es": "Tus perspectivas personalizadas aparecerán aquí cada domingo.", "pt-BR": "Seus insights personalizados aparecerão aqui todo domingo."},
    "Your personalized insights will appear here on Sunday": {"es": "Tus perspectivas personalizadas aparecerán aquí el domingo", "pt-BR": "Seus insights personalizados aparecerão aqui no domingo"},
    "Your progress will be lost. You can start this journey again later.": {"es": "Tu progreso se perderá. Puedes comenzar este viaje de nuevo más tarde.", "pt-BR": "Seu progresso será perdido. Você pode iniciar esta jornada novamente mais tarde."},
    "Your weekly story will appear here": {"es": "Tu historia semanal aparecerá aquí", "pt-BR": "Sua história semanal aparecerá aqui"},
    "You're on a %lld-day streak!": {"es": "¡Llevas una racha de %lld días!", "pt-BR": "Você está em uma sequência de %lld dias!"},
    
    # Special/Additional
    "%@ circle check-ins": {"es": "%@ registros de círculo", "pt-BR": "%@ check-ins de círculo"},
    "%lld day streak": {"es": "Racha de %lld días", "pt-BR": "Sequência de %lld dias"},
    "%lld day streak!": {"es": "¡Racha de %lld días!", "pt-BR": "Sequência de %lld dias!"},
    "%lld days": {"es": "%lld días", "pt-BR": "%lld dias"},
    "%lld milestones": {"es": "%lld hitos", "pt-BR": "%lld marcos"},
    "%lld min": {"es": "%lld min", "pt-BR": "%lld min"},
    "%lld members": {"es": "%lld miembros", "pt-BR": "%lld membros"},
    "%lld star%@": {"es": "%lld estrella%@", "pt-BR": "%lld estrela%@"},
    "%lld%% translated": {"es": "%lld%% traducido", "pt-BR": "%lld%% traduzido"},
    "100% translated": {"es": "100% traducido", "pt-BR": "100% traduzido"},
    "3x more likely to reach goals together!": {"es": "¡3 veces más probable alcanzar metas juntos!", "pt-BR": "3x mais provável alcançar metas juntos!"},
    "5-4-3-2-1 Grounding": {"es": "Conexión a tierra 5-4-3-2-1", "pt-BR": "Aterramento 5-4-3-2-1"},
    "Currently enrolled in \"%@\"": {"es": "Actualmente inscrito en \"%@\"", "pt-BR": "Atualmente inscrito em \"%@\""},
    "Complete or exit your current journey to start this one.": {"es": "Completa o sal de tu viaje actual para comenzar este.", "pt-BR": "Complete ou saia da sua jornada atual para iniciar esta."},
    "Feel gentle vibrations to calm your nervous system": {"es": "Siente vibraciones suaves para calmar tu sistema nervioso", "pt-BR": "Sinta vibrações suaves para acalmar seu sistema nervoso"},
    "Guided routines coming soon...": {"es": "Rutinas guiadas próximamente...", "pt-BR": "Rotinas guiadas em breve..."},
    "Log your moods, complete quests, and do exercises throughout the week. Your personalized insights will appear here every Sunday.": {"es": "Registra tus estados de ánimo, completa misiones y haz ejercicios durante la semana. Tus perspectivas personalizadas aparecerán aquí cada domingo.", "pt-BR": "Registre seus humores, complete missões e faça exercícios durante a semana. Seus insights personalizados aparecerão aqui todo domingo."},
    "Purchase Error": {"es": "Error de compra", "pt-BR": "Erro de compra"},
    "Welcome, Buddy!": {"es": "¡Bienvenido, compañero!", "pt-BR": "Bem-vindo, parceiro!"},
    "e.g., \"When I'm feeling overwhelmed at work\"": {"es": "ej., \"Cuando me siento abrumado en el trabajo\"", "pt-BR": "ex., \"Quando me sinto sobrecarregado no trabalho\""},
    "e.g., A calm ocean sunset with palm trees": {"es": "ej., Una puesta de sol calmada en el océano con palmeras", "pt-BR": "ex., Um pôr do sol calmo no oceano com palmeiras"},
    "e.g., A peaceful moment of clarity after a storm...": {"es": "ej., Un momento de paz y claridad después de una tormenta...", "pt-BR": "ex., Um momento de paz e clareza após uma tempestade..."},
    "e.g., peaceful forest, ocean sunset": {"es": "ej., bosque tranquilo, puesta de sol en el océano", "pt-BR": "ex., floresta tranquila, pôr do sol no oceano"},
    "friend@example.com": {"es": "amigo@ejemplo.com", "pt-BR": "amigo@exemplo.com"},
    "handle": {"es": "identificador", "pt-BR": "identificador"},
    "s": {"es": "s", "pt-BR": "s"},
    "vs last assessment": {"es": "vs última evaluación", "pt-BR": "vs última avaliação"},
    "+%lld XP": {"es": "+%lld XP", "pt-BR": "+%lld XP"},
    "%@ style": {"es": "Estilo %@", "pt-BR": "Estilo %@"},
    "Achievements": {"es": "Logros", "pt-BR": "Conquistas"},
    "Analyze Thought Record": {"es": "Analizar registro de pensamientos", "pt-BR": "Analisar registro de pensamentos"},
    "Chat": {"es": "Chat", "pt-BR": "Chat"},
    "Error: %@": {"es": "Error: %@", "pt-BR": "Erro: %@"},
    "Generating": {"es": "Generando", "pt-BR": "Gerando"},
    "Loading": {"es": "Cargando", "pt-BR": "Carregando"},
    "New Achievements": {"es": "Nuevos logros", "pt-BR": "Novas conquistas"},
}

def main():
    # Load xcstrings file
    xcstrings_path = 'apps/ios/MindFriendApp/Resources/Localizable.xcstrings'
    with open(xcstrings_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    strings = data.get('strings', {})
    translated_count = 0
    missing_count = 0
    
    for key, value in strings.items():
        localizations = value.get('localizations', {})
        
        # Check if translation exists in our dictionary
        if key in TRANSLATIONS:
            trans = TRANSLATIONS[key]
            
            # Add Spanish translation
            if 'es' in trans:
                if 'es' not in localizations:
                    localizations['es'] = {}
                localizations['es']['stringUnit'] = {
                    'state': 'translated',
                    'value': trans['es']
                }
            
            # Add Portuguese-BR translation
            if 'pt-BR' in trans:
                if 'pt-BR' not in localizations:
                    localizations['pt-BR'] = {}
                localizations['pt-BR']['stringUnit'] = {
                    'state': 'translated',
                    'value': trans['pt-BR']
                }
            
            value['localizations'] = localizations
            translated_count += 1
        else:
            # Check if still missing
            es_loc = localizations.get('es', {})
            es_unit = es_loc.get('stringUnit', {})
            if not es_unit.get('value'):
                missing_count += 1
    
    # Save updated file
    with open(xcstrings_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Applied {translated_count} translations from dictionary")
    print(f"Still missing: {missing_count} strings")

if __name__ == '__main__':
    main()
