#!/usr/bin/env python3
"""
Translate remaining missing strings in Localizable.xcstrings - Batch 4 (Final)
"""
import json

# Final translations batch
TRANSLATIONS = {
    "''": {"es": "''", "pt-BR": "''"},
    "Dream Notes (Optional)": {"es": "Notas de sueños (opcional)", "pt-BR": "Notas de sonhos (opcional)"},
    "Dynamic backgrounds & visual effects": {"es": "Fondos dinámicos y efectos visuales", "pt-BR": "Fundos dinâmicos e efeitos visuais"},
    "Mark stories as favorites to see them here": {"es": "Marca historias como favoritas para verlas aquí", "pt-BR": "Marque histórias como favoritas para vê-las aqui"},
    "Marks this cognitive reframe as helpful and records your feedback": {"es": "Marca esta reformulación cognitiva como útil y registra tu comentario", "pt-BR": "Marca esta reformulação cognitiva como útil e registra seu feedback"},
    "Match %@": {"es": "Coincidencia %@", "pt-BR": "Combinação %@"},
    "Match Created": {"es": "Coincidencia creada", "pt-BR": "Combinação criada"},
    "Match Details": {"es": "Detalles de la coincidencia", "pt-BR": "Detalhes da combinação"},
    "Matches": {"es": "Coincidencias", "pt-BR": "Combinações"},
    "Max Tier Reached!": {"es": "¡Nivel máximo alcanzado!", "pt-BR": "Nível máximo alcançado!"},
    "Maximum interventions per day": {"es": "Máximo de intervenciones por día", "pt-BR": "Máximo de intervenções por dia"},
    "Mentee Request": {"es": "Solicitud de aprendiz", "pt-BR": "Solicitação de mentorado"},
    "Mentorship Match": {"es": "Coincidencia de mentoría", "pt-BR": "Combinação de mentoria"},
    "Mentorship Profile": {"es": "Perfil de mentoría", "pt-BR": "Perfil de mentoria"},
    "Message (Optional)": {"es": "Mensaje (opcional)", "pt-BR": "Mensagem (opcional)"},
    "Milestone Story": {"es": "Historia de hito", "pt-BR": "História de marco"},
    "Milestones Achieved": {"es": "Hitos alcanzados", "pt-BR": "Marcos alcançados"},
    "MindFriend %@": {"es": "MindFriend %@", "pt-BR": "MindFriend %@"},
    "MindFriend Wellness Journey": {"es": "Viaje de bienestar MindFriend", "pt-BR": "Jornada de bem-estar MindFriend"},
    "MindFriend learns what helps people feel better by analyzing anonymous patterns across our community. No personal information is ever shared.": {"es": "MindFriend aprende qué ayuda a las personas a sentirse mejor analizando patrones anónimos de nuestra comunidad. Nunca se comparte información personal.", "pt-BR": "MindFriend aprende o que ajuda as pessoas a se sentirem melhor analisando padrões anônimos da nossa comunidade. Nenhuma informação pessoal é compartilhada."},
    "MindFriend will proactively offer calming interventions before meetings, deadlines, and other stressful calendar events.": {"es": "MindFriend ofrecerá proactivamente intervenciones calmantes antes de reuniones, plazos y otros eventos estresantes del calendario.", "pt-BR": "MindFriend oferecerá proativamente intervenções calmantes antes de reuniões, prazos e outros eventos estressantes do calendário."},
    "Minimal (rare suggestions)": {"es": "Mínimo (sugerencias raras)", "pt-BR": "Mínimo (sugestões raras)"},
    "Monitored Calendars": {"es": "Calendarios monitoreados", "pt-BR": "Calendários monitorados"},
    "Month": {"es": "Mes", "pt-BR": "Mês"},
    "Mood Patterns": {"es": "Patrones de ánimo", "pt-BR": "Padrões de humor"},
    "Mood Throughout the Year": {"es": "Ánimo durante el año", "pt-BR": "Humor ao longo do ano"},
    "Mood Trend": {"es": "Tendencia de ánimo", "pt-BR": "Tendência de humor"},
    "Mood: %lld/10": {"es": "Ánimo: %lld/10", "pt-BR": "Humor: %lld/10"},
    "Morning Check-In": {"es": "Registro matutino", "pt-BR": "Check-in matinal"},
    "Most Available": {"es": "Más disponible", "pt-BR": "Mais disponível"},
    "Most Common Patterns": {"es": "Patrones más comunes", "pt-BR": "Padrões mais comuns"},
    "Move your camera to scan the floor": {"es": "Mueve tu cámara para escanear el piso", "pt-BR": "Mova sua câmera para escanear o chão"},
    "My Patterns": {"es": "Mis patrones", "pt-BR": "Meus padrões"},
    "My Saved Exercises": {"es": "Mis ejercicios guardados", "pt-BR": "Meus exercícios salvos"},
    "My wellness report from MindFriend": {"es": "Mi reporte de bienestar de MindFriend", "pt-BR": "Meu relatório de bem-estar do MindFriend"},
    "No Mentors Found": {"es": "No se encontraron mentores", "pt-BR": "Nenhum mentor encontrado"},
    "No Recommendations Yet": {"es": "Aún no hay recomendaciones", "pt-BR": "Nenhuma recomendação ainda"},
    "No Sessions Yet": {"es": "Aún no hay sesiones", "pt-BR": "Nenhuma sessão ainda"},
    "No Shield Events Yet": {"es": "Aún no hay eventos de escudo", "pt-BR": "Nenhum evento de escudo ainda"},
    "No Strategies Yet": {"es": "Aún no hay estrategias", "pt-BR": "Nenhuma estratégia ainda"},
    "No Transactions": {"es": "No hay transacciones", "pt-BR": "Nenhuma transação"},
    "No Watch": {"es": "Sin reloj", "pt-BR": "Sem relógio"},
    "No baseline calculated": {"es": "No hay línea base calculada", "pt-BR": "Nenhuma linha de base calculada"},
    "No calendars available": {"es": "No hay calendarios disponibles", "pt-BR": "Nenhum calendário disponível"},
    "No capacity data": {"es": "No hay datos de capacidad", "pt-BR": "Nenhum dado de capacidade"},
    "No coaching suggestions will appear during these hours.": {"es": "No aparecerán sugerencias de coaching durante estas horas.", "pt-BR": "Nenhuma sugestão de coaching aparecerá durante essas horas."},
    "No emotion detected yet": {"es": "Aún no hay emoción detectada", "pt-BR": "Nenhuma emoção detectada ainda"},
    "No interventions will be delivered during quiet hours": {"es": "No se entregarán intervenciones durante las horas de silencio", "pt-BR": "Nenhuma intervenção será entregue durante as horas de silêncio"},
    "No markers to undo": {"es": "No hay marcadores para deshacer", "pt-BR": "Nenhum marcador para desfazer"},
    "No mood data available for this year": {"es": "No hay datos de ánimo disponibles para este año", "pt-BR": "Nenhum dado de humor disponível para este ano"},
    "No objects to remove": {"es": "No hay objetos para eliminar", "pt-BR": "Nenhum objeto para remover"},
    "No supporters found yet": {"es": "Aún no hay seguidores encontrados", "pt-BR": "Nenhum apoiador encontrado ainda"},
    "No timeline data": {"es": "No hay datos de línea de tiempo", "pt-BR": "Nenhum dado de linha do tempo"},
    "No trajectory data yet": {"es": "Aún no hay datos de trayectoria", "pt-BR": "Nenhum dado de trajetória ainda"},
    "No transactions recorded for this period.": {"es": "No hay transacciones registradas para este período.", "pt-BR": "Nenhuma transação registrada para este período."},
    "No warning signs selected": {"es": "No hay señales de alerta seleccionadas", "pt-BR": "Nenhum sinal de alerta selecionado"},
    "Non-AR": {"es": "No-RA", "pt-BR": "Não-RA"},
    "Not available": {"es": "No disponible", "pt-BR": "Não disponível"},
    "Not enough data": {"es": "No hay suficientes datos", "pt-BR": "Dados insuficientes"},
    "Not enough data for yearly summary yet": {"es": "Aún no hay suficientes datos para el resumen anual", "pt-BR": "Ainda não há dados suficientes para o resumo anual"},
    "Not helpful": {"es": "No fue útil", "pt-BR": "Não foi útil"},
    "Not yet": {"es": "Aún no", "pt-BR": "Ainda não"},
    "Notice when they appear and try the suggested reframes.": {"es": "Nota cuándo aparecen e intenta las reformulaciones sugeridas.", "pt-BR": "Note quando aparecem e tente as reformulações sugeridas."},
    "Noticed something": {"es": "Noté algo", "pt-BR": "Notei algo"},
    "Notification": {"es": "Notificación", "pt-BR": "Notificação"},
    "Notification delivery coming in Phase 2": {"es": "Entrega de notificaciones en la Fase 2", "pt-BR": "Entrega de notificações na Fase 2"},
    "Number of Employees": {"es": "Número de empleados", "pt-BR": "Número de funcionários"},
    "Peer Support Alerts": {"es": "Alertas de apoyo entre pares", "pt-BR": "Alertas de apoio entre pares"},
    "Pending Requests (%lld)": {"es": "Solicitudes pendientes (%lld)", "pt-BR": "Solicitações pendentes (%lld)"},
    "Phase Objectives": {"es": "Objetivos de fase", "pt-BR": "Objetivos da fase"},
    "Phase Progress": {"es": "Progreso de fase", "pt-BR": "Progresso da fase"},
    "Place at least one object first": {"es": "Coloca al menos un objeto primero", "pt-BR": "Coloque pelo menos um objeto primeiro"},
    "Please go back and select at least 2 warning signs that feel familiar to you.": {"es": "Por favor regresa y selecciona al menos 2 señales de alerta que te resulten familiares.", "pt-BR": "Por favor volte e selecione pelo menos 2 sinais de alerta que pareçam familiares para você."},
    "Please wait while your artwork is being created": {"es": "Por favor espera mientras se crea tu obra de arte", "pt-BR": "Por favor aguarde enquanto sua arte está sendo criada"},
    "Please wait while your profile picture is being generated": {"es": "Por favor espera mientras se genera tu foto de perfil", "pt-BR": "Por favor aguarde enquanto sua foto de perfil está sendo gerada"},
    "Positive influence": {"es": "Influencia positiva", "pt-BR": "Influência positiva"},
    "Predicted mood:": {"es": "Ánimo predicho:", "pt-BR": "Humor previsto:"},
    "Preferences saved": {"es": "Preferencias guardadas", "pt-BR": "Preferências salvas"},
    "Preferred Activities": {"es": "Actividades preferidas", "pt-BR": "Atividades preferidas"},
    "Premium feature - tap to upgrade": {"es": "Función premium - toca para mejorar", "pt-BR": "Recurso premium - toque para atualizar"},
    "Premium: Unlimited generations": {"es": "Premium: Generaciones ilimitadas", "pt-BR": "Premium: Gerações ilimitadas"},
    "Preparation Tips": {"es": "Consejos de preparación", "pt-BR": "Dicas de preparação"},
    "Prepare for Better Sleep": {"es": "Prepárate para un mejor sueño", "pt-BR": "Prepare-se para um sono melhor"},
    "Preview showing, refining details": {"es": "Vista previa mostrando, refinando detalles", "pt-BR": "Visualização mostrando, refinando detalhes"},
    "Privacy & Sharing": {"es": "Privacidad y compartir", "pt-BR": "Privacidade e compartilhamento"},
    "Privacy Guarantees": {"es": "Garantías de privacidad", "pt-BR": "Garantias de privacidade"},
    "Privacy settings coming soon": {"es": "Configuración de privacidad próximamente", "pt-BR": "Configurações de privacidade em breve"},
    "Proceed to %@ step": {"es": "Proceder al paso %@", "pt-BR": "Prosseguir para o passo %@"},
    "Profile picture description": {"es": "Descripción de foto de perfil", "pt-BR": "Descrição da foto de perfil"},
    "Program Intensity": {"es": "Intensidad del programa", "pt-BR": "Intensidade do programa"},
    "Progress to %@": {"es": "Progreso hacia %@", "pt-BR": "Progresso para %@"},
    "Progress: %@ step": {"es": "Progreso: paso %@", "pt-BR": "Progresso: passo %@"},
    "Protected": {"es": "Protegido", "pt-BR": "Protegido"},
    "Receive Recommendations": {"es": "Recibir recomendaciones", "pt-BR": "Receber recomendações"},
    "Receive a personalized morning briefing with mood prediction, quest, and calendar events.": {"es": "Recibe un resumen matutino personalizado con predicción de ánimo, misión y eventos del calendario.", "pt-BR": "Receba um resumo matinal personalizado com previsão de humor, missão e eventos do calendário."},
    "Recent Conversations": {"es": "Conversaciones recientes", "pt-BR": "Conversas recentes"},
    "Recent Life Events": {"es": "Eventos de vida recientes", "pt-BR": "Eventos de vida recentes"},
    "Recently Active": {"es": "Activo recientemente", "pt-BR": "Ativo recentemente"},
    "Recommendations Disabled": {"es": "Recomendaciones deshabilitadas", "pt-BR": "Recomendações desativadas"},
    "Recommendations are based on patterns from people in similar situations. You can give feedback to improve relevance.": {"es": "Las recomendaciones se basan en patrones de personas en situaciones similares. Puedes dar comentarios para mejorar la relevancia.", "pt-BR": "As recomendações são baseadas em padrões de pessoas em situações semelhantes. Você pode dar feedback para melhorar a relevância."},
    "Recommended for you: %@, %@": {"es": "Recomendado para ti: %@, %@", "pt-BR": "Recomendado para você: %@, %@"},
    "Recovery": {"es": "Recuperación", "pt-BR": "Recuperação"},
    "Reduce description to 200 characters or less": {"es": "Reduce la descripción a 200 caracteres o menos", "pt-BR": "Reduza a descrição para 200 caracteres ou menos"},
    "Refining your artwork...": {"es": "Refinando tu obra de arte...", "pt-BR": "Refinando sua arte..."},
    "Refining your image...": {"es": "Refinando tu imagen...", "pt-BR": "Refinando sua imagem..."},
    "Reflection Questions": {"es": "Preguntas de reflexión", "pt-BR": "Perguntas de reflexão"},
    "Reframe:": {"es": "Reformulación:", "pt-BR": "Reformulação:"},
    "Reframing question: %@": {"es": "Pregunta de reformulación: %@", "pt-BR": "Pergunta de reformulação: %@"},
    "Rehearsal Studio": {"es": "Estudio de ensayo", "pt-BR": "Estúdio de ensaio"},
    "Remove last object": {"es": "Eliminar último objeto", "pt-BR": "Remover último objeto"},
    "Removes the last placed marker": {"es": "Elimina el último marcador colocado", "pt-BR": "Remove o último marcador colocado"},
    "Removes the last placed object": {"es": "Elimina el último objeto colocado", "pt-BR": "Remove o último objeto colocado"},
    "Reports": {"es": "Reportes", "pt-BR": "Relatórios"},
    "Request Access": {"es": "Solicitar acceso", "pt-BR": "Solicitar acesso"},
    "Reset all preferences to warm tone, standard length, and metrics included.": {"es": "Restablecer todas las preferencias a tono cálido, longitud estándar y métricas incluidas.", "pt-BR": "Redefinir todas as preferências para tom caloroso, comprimento padrão e métricas incluídas."},
    "Resting HRV": {"es": "VFC en reposo", "pt-BR": "VFC em repouso"},
    "Resting Heart Rate": {"es": "Frecuencia cardíaca en reposo", "pt-BR": "Frequência cardíaca em repouso"},
    "Resume exercise": {"es": "Reanudar ejercicio", "pt-BR": "Retomar exercício"},
    "Retry loading AR exercises": {"es": "Reintentar cargar ejercicios de RA", "pt-BR": "Tentar novamente carregar exercícios de RA"},
    "Return to home screen": {"es": "Volver a la pantalla de inicio", "pt-BR": "Voltar para a tela inicial"},
    "Rewrite Your Thought": {"es": "Reescribe tu pensamiento", "pt-BR": "Reescreva seu pensamento"},
    "Routine Complete!": {"es": "¡Rutina completada!", "pt-BR": "Rotina completa!"},
    "Safe Space Created!": {"es": "¡Espacio seguro creado!", "pt-BR": "Espaço seguro criado!"},
    "Samples": {"es": "Muestras", "pt-BR": "Amostras"},
    "Save Check-In": {"es": "Guardar registro", "pt-BR": "Salvar check-in"},
    "Save Safe Space": {"es": "Guardar espacio seguro", "pt-BR": "Salvar espaço seguro"},
    "Save safe space": {"es": "Guardar espacio seguro", "pt-BR": "Salvar espaço seguro"},
    "Save your current safe space configuration": {"es": "Guarda tu configuración actual de espacio seguro", "pt-BR": "Salve sua configuração atual de espaço seguro"},
    "Saving check-in...": {"es": "Guardando registro...", "pt-BR": "Salvando check-in..."},
    "Scanning your environment...": {"es": "Escaneando tu entorno...", "pt-BR": "Escaneando seu ambiente..."},
    "Score: %lld/100": {"es": "Puntuación: %lld/100", "pt-BR": "Pontuação: %lld/100"},
    "Seasonal Patterns": {"es": "Patrones estacionales", "pt-BR": "Padrões sazonais"},
    "Second dose": {"es": "Segunda dosis", "pt-BR": "Segunda dose"},
    "See What's Contributed": {"es": "Ver lo que se contribuye", "pt-BR": "Ver o que é contribuído"},
    "Seeking mentor": {"es": "Buscando mentor", "pt-BR": "Buscando mentor"},
    "Select 8-12 values that are most important to you": {"es": "Selecciona 8-12 valores que sean más importantes para ti", "pt-BR": "Selecione 8-12 valores que são mais importantes para você"},
    "Select All": {"es": "Seleccionar todo", "pt-BR": "Selecionar tudo"},
    "Select any that feel familiar when you're struggling": {"es": "Selecciona cualquiera que te resulte familiar cuando estás luchando", "pt-BR": "Selecione qualquer um que pareça familiar quando você está lutando"},
    "Select people who can receive alerts about your social wellbeing.": {"es": "Selecciona personas que puedan recibir alertas sobre tu bienestar social.", "pt-BR": "Selecione pessoas que podem receber alertas sobre seu bem-estar social."},
    "Send Message": {"es": "Enviar mensaje", "pt-BR": "Enviar mensagem"},
    "Send Request": {"es": "Enviar solicitud", "pt-BR": "Enviar solicitação"},
    "Sensitivity Level": {"es": "Nivel de sensibilidad", "pt-BR": "Nível de sensibilidade"},
    "Session Preferences": {"es": "Preferencias de sesión", "pt-BR": "Preferências de sessão"},
    "Session Stats": {"es": "Estadísticas de sesión", "pt-BR": "Estatísticas de sessão"},
    "Session Timeline": {"es": "Línea de tiempo de sesión", "pt-BR": "Linha do tempo da sessão"},
    "Set Up Your Warning Signs": {"es": "Configura tus señales de alerta", "pt-BR": "Configure seus sinais de alerta"},
    "Share Your Journey": {"es": "Comparte tu viaje", "pt-BR": "Compartilhe sua jornada"},
    "Share a coping strategy that helps you...": {"es": "Comparte una estrategia de afrontamiento que te ayuda...", "pt-BR": "Compartilhe uma estratégia de enfrentamento que ajuda você..."},
    "Share a new strategy": {"es": "Compartir una nueva estrategia", "pt-BR": "Compartilhar uma nova estratégia"},
    "Share a strategy": {"es": "Compartir una estrategia", "pt-BR": "Compartilhar uma estratégia"},
    "Share what you're hoping to learn and why you think they'd be a good fit": {"es": "Comparte lo que esperas aprender y por qué crees que serían una buena opción", "pt-BR": "Compartilhe o que você espera aprender e por que acha que eles seriam uma boa opção"},
    "Shields are earned every 7 days of consistent questing": {"es": "Los escudos se ganan cada 7 días de misiones consistentes", "pt-BR": "Escudos são conquistados a cada 7 dias de missões consistentes"},
    "Show less": {"es": "Mostrar menos", "pt-BR": "Mostrar menos"},
    "Show less details": {"es": "Mostrar menos detalles", "pt-BR": "Mostrar menos detalhes"},
    "Show me my thinking patterns": {"es": "Muéstrame mis patrones de pensamiento", "pt-BR": "Mostre-me meus padrões de pensamento"},
    "Show only recommended for you": {"es": "Mostrar solo recomendados para ti", "pt-BR": "Mostrar apenas recomendados para você"},
    "Show specific numbers like mood scores and quest completion percentages in your stories.": {"es": "Muestra números específicos como puntuaciones de ánimo y porcentajes de finalización de misiones en tus historias.", "pt-BR": "Mostre números específicos como pontuações de humor e porcentagens de conclusão de missões em suas histórias."},
    "Show upcoming events in your briefing.": {"es": "Muestra próximos eventos en tu resumen.", "pt-BR": "Mostre próximos eventos em seu resumo."},
    "Shows additional reflection questions about this thinking pattern": {"es": "Muestra preguntas de reflexión adicionales sobre este patrón de pensamiento", "pt-BR": "Mostra perguntas de reflexão adicionais sobre este padrão de pensamento"},
    "Silent Hours": {"es": "Horas silenciosas", "pt-BR": "Horas silenciosas"},
    "Skip this prompt": {"es": "Omitir esta indicación", "pt-BR": "Pular este prompt"},
    "Sleep Duration": {"es": "Duración del sueño", "pt-BR": "Duração do sono"},
    "Sleep Environment": {"es": "Ambiente de sueño", "pt-BR": "Ambiente de sono"},
    "Sleep Goals": {"es": "Metas de sueño", "pt-BR": "Metas de sono"},
    "Sleep Insights": {"es": "Perspectivas de sueño", "pt-BR": "Insights de sono"},
    "Sleep Quality": {"es": "Calidad del sueño", "pt-BR": "Qualidade do sono"},
    "Sleep Schedule": {"es": "Horario de sueño", "pt-BR": "Horário de sono"},
    "Sleep Time": {"es": "Hora de dormir", "pt-BR": "Hora de dormir"},
    "Sort by": {"es": "Ordenar por", "pt-BR": "Ordenar por"},
    "Speak for at least 3 seconds to analyze your emotional state": {"es": "Habla por al menos 3 segundos para analizar tu estado emocional", "pt-BR": "Fale por pelo menos 3 segundos para analisar seu estado emocional"},
    "Start Another Pathway": {"es": "Comenzar otro camino", "pt-BR": "Iniciar outro caminho"},
    "Start Date": {"es": "Fecha de inicio", "pt-BR": "Data de início"},
    "Start Recommended Exercise": {"es": "Iniciar ejercicio recomendado", "pt-BR": "Iniciar exercício recomendado"},
    "Start Tracking Your Sleep": {"es": "Comienza a rastrear tu sueño", "pt-BR": "Comece a rastrear seu sono"},
    "Start Wind-Down": {"es": "Iniciar relajación", "pt-BR": "Iniciar relaxamento"},
    "Start another pathway": {"es": "Comenzar otro camino", "pt-BR": "Iniciar outro caminho"},
    "Start recommended exercise": {"es": "Iniciar ejercicio recomendado", "pt-BR": "Iniciar exercício recomendado"},
    "Start time": {"es": "Hora de inicio", "pt-BR": "Hora de início"},
    "Start tracking to see your mood trends": {"es": "Comienza a rastrear para ver tus tendencias de ánimo", "pt-BR": "Comece a rastrear para ver suas tendências de humor"},
    "Start tracking your progress": {"es": "Comienza a rastrear tu progreso", "pt-BR": "Comece a rastrear seu progresso"},
    "Start voice guidance": {"es": "Iniciar guía de voz", "pt-BR": "Iniciar guia de voz"},
    "Status": {"es": "Estado", "pt-BR": "Status"},
    "Step %lld/%lld": {"es": "Paso %lld/%lld", "pt-BR": "Passo %lld/%lld"},
    "Stop voice guidance": {"es": "Detener guía de voz", "pt-BR": "Parar guia de voz"},
    "Story Length": {"es": "Longitud de historia", "pt-BR": "Comprimento da história"},
    "Streak Day: %lld": {"es": "Día de racha: %lld", "pt-BR": "Dia de sequência: %lld"},
    "Stress Signature": {"es": "Firma de estrés", "pt-BR": "Assinatura de estresse"},
    "Stress Threshold": {"es": "Umbral de estrés", "pt-BR": "Limite de estresse"},
    "Submit %@ as feedback": {"es": "Enviar %@ como comentario", "pt-BR": "Enviar %@ como feedback"},
    "Submit Inquiry": {"es": "Enviar consulta", "pt-BR": "Enviar consulta"},
    "Subscribe to %@/%@": {"es": "Suscribirse a %@/%@", "pt-BR": "Assinar %@/%@"},
    "Suggested Support": {"es": "Apoyo sugerido", "pt-BR": "Apoio sugerido"},
    "Sync heart rate data daily": {"es": "Sincronizar datos de frecuencia cardíaca diariamente", "pt-BR": "Sincronizar dados de frequência cardíaca diariamente"},
    "Take a quick check-in to set a baseline and unlock personalized goals.": {"es": "Haz un registro rápido para establecer una línea base y desbloquear metas personalizadas.", "pt-BR": "Faça um check-in rápido para estabelecer uma linha de base e desbloquear metas personalizadas."},
    "Tap anywhere to continue": {"es": "Toca en cualquier lugar para continuar", "pt-BR": "Toque em qualquer lugar para continuar"},
    "Tap for preparation tips": {"es": "Toca para consejos de preparación", "pt-BR": "Toque para dicas de preparação"},
    "Tap objects in your environment": {"es": "Toca objetos en tu entorno", "pt-BR": "Toque objetos em seu ambiente"},
    "Tap to add (%lld remaining)": {"es": "Toca para agregar (%lld restantes)", "pt-BR": "Toque para adicionar (%lld restantes)"},
    "Tap to calculate": {"es": "Toca para calcular", "pt-BR": "Toque para calcular"},
    "Tap to select, then tap in scene to place": {"es": "Toca para seleccionar, luego toca en la escena para colocar", "pt-BR": "Toque para selecionar, depois toque na cena para posicionar"},
    "Tap to turn coaching on or off": {"es": "Toca para activar o desactivar el coaching", "pt-BR": "Toque para ativar ou desativar o coaching"},
    "Target Bedtime": {"es": "Hora de dormir objetivo", "pt-BR": "Hora de dormir alvo"},
    "Target Sleep Duration": {"es": "Duración de sueño objetivo", "pt-BR": "Duração de sono alvo"},
    "Target Wake Time": {"es": "Hora de despertar objetivo", "pt-BR": "Hora de acordar alvo"},
    "Target: Reduce debt by %lld points": {"es": "Objetivo: Reducir deuda en %lld puntos", "pt-BR": "Objetivo: Reduzir dívida em %lld pontos"},
    "Tell them about yourself": {"es": "Cuéntales sobre ti", "pt-BR": "Conte-lhes sobre você"},
    "Tell us about your team's mental health needs and any specific requirements.": {"es": "Cuéntanos sobre las necesidades de salud mental de tu equipo y cualquier requisito específico.", "pt-BR": "Conte-nos sobre as necessidades de saúde mental da sua equipe e quaisquer requisitos específicos."},
    "Tell us more (optional)": {"es": "Cuéntanos más (opcional)", "pt-BR": "Conte-nos mais (opcional)"},
    "Tell us more...": {"es": "Cuéntanos más...", "pt-BR": "Conte-nos mais..."},
    "Thank you for engaging": {"es": "Gracias por participar", "pt-BR": "Obrigado por participar"},
    "Thank you for sharing! Your strategy will be reviewed and published soon.": {"es": "¡Gracias por compartir! Tu estrategia será revisada y publicada pronto.", "pt-BR": "Obrigado por compartilhar! Sua estratégia será revisada e publicada em breve."},
    "Thanks!": {"es": "¡Gracias!", "pt-BR": "Obrigado!"},
    "The agent hasn't taken any actions yet. Enable the agent and it will start monitoring your patterns.": {"es": "El agente aún no ha tomado ninguna acción. Habilita el agente y comenzará a monitorear tus patrones.", "pt-BR": "O agente ainda não realizou nenhuma ação. Ative o agente e ele começará a monitorar seus padrões."},
    "The coaching feature helps you recognize and reframe thinking patterns in real-time.": {"es": "La función de coaching te ayuda a reconocer y reformular patrones de pensamiento en tiempo real.", "pt-BR": "O recurso de coaching ajuda você a reconhecer e reformular padrões de pensamento em tempo real."},
    "The default speed for tactile patterns and visual animations. You can adjust this for each session.": {"es": "La velocidad predeterminada para patrones táctiles y animaciones visuales. Puedes ajustar esto para cada sesión.", "pt-BR": "A velocidade padrão para padrões táteis e animações visuais. Você pode ajustar isso para cada sessão."},
    "Their Message": {"es": "Su mensaje", "pt-BR": "A mensagem deles"},
    "Thinking Coach Settings": {"es": "Configuración del coach de pensamiento", "pt-BR": "Configurações do coach de pensamento"},
    "Thinking Patterns Library": {"es": "Biblioteca de patrones de pensamiento", "pt-BR": "Biblioteca de padrões de pensamento"},
    "Third dose": {"es": "Tercera dosis", "pt-BR": "Terceira dose"},
    "This helps": {"es": "Esto ayuda", "pt-BR": "Isso ajuda"},
    "This model has %lld%% accuracy": {"es": "Este modelo tiene %lld%% de precisión", "pt-BR": "Este modelo tem %lld%% de precisão"},
    "This pattern has been detected based on your personal warning signs.": {"es": "Este patrón ha sido detectado basándose en tus señales de alerta personales.", "pt-BR": "Este padrão foi detectado com base em seus sinais de alerta pessoais."},
    "This takes about 3 minutes": {"es": "Esto toma aproximadamente 3 minutos", "pt-BR": "Isso leva cerca de 3 minutos"},
    "This transition has shaped you into someone stronger and wiser. The courage you've shown throughout this journey is remarkable.": {"es": "Esta transición te ha convertido en alguien más fuerte y sabio. El coraje que has mostrado durante este viaje es notable.", "pt-BR": "Esta transição moldou você em alguém mais forte e sábio. A coragem que você demonstrou ao longo desta jornada é notável."},
    "This will analyze your crisis history to update your warning signs. Your existing patterns will be merged with newly discovered ones.": {"es": "Esto analizará tu historial de crisis para actualizar tus señales de alerta. Tus patrones existentes se fusionarán con los recién descubiertos.", "pt-BR": "Isso analisará seu histórico de crises para atualizar seus sinais de alerta. Seus padrões existentes serão mesclados com os recém-descobertos."},
    "Thought Pattern Noticed": {"es": "Patrón de pensamiento detectado", "pt-BR": "Padrão de pensamento detectado"},
    "Thought pattern icon": {"es": "Ícono de patrón de pensamiento", "pt-BR": "Ícone de padrão de pensamento"},
    "Time-Based Themes": {"es": "Temas basados en tiempo", "pt-BR": "Temas baseados em tempo"},
    "Times you typically dismiss:": {"es": "Horas en que típicamente descartas:", "pt-BR": "Horários em que você normalmente dispensa:"},
    "Tips for a good strategy:": {"es": "Consejos para una buena estrategia:", "pt-BR": "Dicas para uma boa estratégia:"},
    "Tips:": {"es": "Consejos:", "pt-BR": "Dicas:"},
    "To:": {"es": "Para:", "pt-BR": "Para:"},
    "Today's Affirmation": {"es": "Afirmación de hoy", "pt-BR": "Afirmação de hoje"},
    "Today's Outlook": {"es": "Perspectiva de hoy", "pt-BR": "Perspectiva de hoje"},
    "Today's Prediction": {"es": "Predicción de hoy", "pt-BR": "Previsão de hoje"},
    "Today's Wellness": {"es": "Bienestar de hoy", "pt-BR": "Bem-estar de hoje"},
    "Today's outlook: %@": {"es": "Perspectiva de hoy: %@", "pt-BR": "Perspectiva de hoje: %@"},
    "Tone": {"es": "Tono", "pt-BR": "Tom"},
    "Top Deposits (Last 30 Days)": {"es": "Principales depósitos (últimos 30 días)", "pt-BR": "Principais depósitos (últimos 30 dias)"},
    "Top Drains (Last 30 Days)": {"es": "Principales drenajes (últimos 30 días)", "pt-BR": "Principais drenos (últimos 30 dias)"},
    "Top Exercises": {"es": "Principales ejercicios", "pt-BR": "Principais exercícios"},
    "Top Supporters": {"es": "Principales apoyos", "pt-BR": "Principais apoiadores"},
    "Total Sessions": {"es": "Sesiones totales", "pt-BR": "Sessões totais"},
    "Track Your Life Events": {"es": "Rastrea tus eventos de vida", "pt-BR": "Rastreie seus eventos de vida"},
    "Track which thinking patterns you encounter most frequently and see trends over time.": {"es": "Rastrea qué patrones de pensamiento encuentras con más frecuencia y ve tendencias a lo largo del tiempo.", "pt-BR": "Rastreie quais padrões de pensamento você encontra com mais frequência e veja tendências ao longo do tempo."},
    "Track your mood regularly to see long-term patterns and insights about your wellness journey.": {"es": "Rastrea tu estado de ánimo regularmente para ver patrones a largo plazo y perspectivas sobre tu viaje de bienestar.", "pt-BR": "Rastreie seu humor regularmente para ver padrões de longo prazo e insights sobre sua jornada de bem-estar."},
    "Track your sleep for at least 7 days to receive personalized insights": {"es": "Rastrea tu sueño por al menos 7 días para recibir perspectivas personalizadas", "pt-BR": "Rastreie seu sono por pelo menos 7 dias para receber insights personalizados"},
    "Transaction Breakdown": {"es": "Desglose de transacciones", "pt-BR": "Detalhamento de transações"},
    "Trend": {"es": "Tendencia", "pt-BR": "Tendência"},
    "Trigger phrase: %@": {"es": "Frase desencadenante: %@", "pt-BR": "Frase gatilho: %@"},
    "Trusted Supporters": {"es": "Apoyos de confianza", "pt-BR": "Apoiadores de confiança"},
    "Try adjusting your search criteria or check back later": {"es": "Intenta ajustar tus criterios de búsqueda o vuelve más tarde", "pt-BR": "Tente ajustar seus critérios de busca ou volte mais tarde"},
    "Unable to Load Patterns": {"es": "No se pueden cargar los patrones", "pt-BR": "Não foi possível carregar os padrões"},
    "Unable to load data": {"es": "No se pueden cargar los datos", "pt-BR": "Não foi possível carregar os dados"},
    "Unable to load patterns": {"es": "No se pueden cargar los patrones", "pt-BR": "Não foi possível carregar os padrões"},
    "Undo last marker": {"es": "Deshacer último marcador", "pt-BR": "Desfazer último marcador"},
    "Unknown": {"es": "Desconocido", "pt-BR": "Desconhecido"},
    "Unlimited generations": {"es": "Generaciones ilimitadas", "pt-BR": "Gerações ilimitadas"},
    "Updated %@": {"es": "Actualizado %@", "pt-BR": "Atualizado %@"},
    "Upgrade to Generate": {"es": "Mejora para generar", "pt-BR": "Atualize para gerar"},
    "Upgrade to Premium for unlimited generations": {"es": "Mejora a Premium para generaciones ilimitadas", "pt-BR": "Atualize para Premium para gerações ilimitadas"},
    "Upgrade to Unlock": {"es": "Mejora para desbloquear", "pt-BR": "Atualize para desbloquear"},
    "Upgrade to have natural voice conversations with your AI companion. Talk hands-free, get real-time responses, and experience a more personal connection.": {"es": "Mejora para tener conversaciones de voz naturales con tu compañero de IA. Habla manos libres, obtén respuestas en tiempo real y experimenta una conexión más personal.", "pt-BR": "Atualize para ter conversas de voz naturais com seu companheiro de IA. Fale sem usar as mãos, obtenha respostas em tempo real e experimente uma conexão mais pessoal."},
    "Upgrade to premium": {"es": "Mejora a premium", "pt-BR": "Atualize para premium"},
    "Upload photo from library": {"es": "Subir foto de la biblioteca", "pt-BR": "Enviar foto da biblioteca"},
    "Uploading...": {"es": "Subiendo...", "pt-BR": "Enviando..."},
    "Use Photo": {"es": "Usar foto", "pt-BR": "Usar foto"},
    "Use gentle vibrations, calming visuals, or nature sounds to regulate your nervous system": {"es": "Usa vibraciones suaves, visuales calmantes o sonidos de la naturaleza para regular tu sistema nervioso", "pt-BR": "Use vibrações suaves, visuais calmantes ou sons da natureza para regular seu sistema nervoso"},
    "Using device voice": {"es": "Usando voz del dispositivo", "pt-BR": "Usando voz do dispositivo"},
    "Using non-AR fallback mode": {"es": "Usando modo de respaldo sin RA", "pt-BR": "Usando modo de fallback sem RA"},
    "Using sample data. Backend integration in progress.": {"es": "Usando datos de muestra. Integración de backend en progreso.", "pt-BR": "Usando dados de amostra. Integração de backend em progresso."},
    "Vacation Period": {"es": "Período de vacaciones", "pt-BR": "Período de férias"},
    "Verified Mentor": {"es": "Mentor verificado", "pt-BR": "Mentor verificado"},
    "View Breakdown": {"es": "Ver desglose", "pt-BR": "Ver detalhamento"},
    "View My Matches (%lld)": {"es": "Ver mis coincidencias (%lld)", "pt-BR": "Ver minhas combinações (%lld)"},
    "View Reports": {"es": "Ver reportes", "pt-BR": "Ver relatórios"},
    "Visual Experience": {"es": "Experiencia visual", "pt-BR": "Experiência visual"},
    "Voice Mode is Premium": {"es": "El modo de voz es Premium", "pt-BR": "O modo de voz é Premium"},
    "Watch Connection": {"es": "Conexión de reloj", "pt-BR": "Conexão de relógio"},
    "We need a bit more data to create meaningful patterns. Keep tracking for at least 7 days.": {"es": "Necesitamos un poco más de datos para crear patrones significativos. Sigue rastreando por al menos 7 días.", "pt-BR": "Precisamos de um pouco mais de dados para criar padrões significativos. Continue rastreando por pelo menos 7 dias."},
    "We're collecting data about your social connections": {"es": "Estamos recopilando datos sobre tus conexiones sociales", "pt-BR": "Estamos coletando dados sobre suas conexões sociais"},
    "Weakest: %@": {"es": "Más débil: %@", "pt-BR": "Mais fraco: %@"},
    "Weekly": {"es": "Semanal", "pt-BR": "Semanal"},
    "Weekly Change: %@": {"es": "Cambio semanal: %@", "pt-BR": "Mudança semanal: %@"},
    "Welcome to %@. Your journey continues.": {"es": "Bienvenido a %@. Tu viaje continúa.", "pt-BR": "Bem-vindo a %@. Sua jornada continua."},
    "Wellness": {"es": "Bienestar", "pt-BR": "Bem-estar"},
    "Wellness Breakdown": {"es": "Desglose de bienestar", "pt-BR": "Detalhamento de bem-estar"},
    "Went to bed": {"es": "Se acostó", "pt-BR": "Foi para a cama"},
    "What Contributed": {"es": "Lo que contribuyó", "pt-BR": "O que contribuiu"},
    "What This Means": {"es": "Lo que esto significa", "pt-BR": "O que isso significa"},
    "What We Never Store:": {"es": "Lo que nunca almacenamos:", "pt-BR": "O que nunca armazenamos:"},
    "What We Noticed": {"es": "Lo que notamos", "pt-BR": "O que notamos"},
    "What You're Seeking": {"es": "Lo que buscas", "pt-BR": "O que você busca"},
    "What could be improved?": {"es": "¿Qué podría mejorarse?", "pt-BR": "O que poderia ser melhorado?"},
    "What helps:": {"es": "Lo que ayuda:", "pt-BR": "O que ajuda:"},
    "What is this?": {"es": "¿Qué es esto?", "pt-BR": "O que é isso?"},
    "What it means": {"es": "Lo que significa", "pt-BR": "O que significa"},
    "What's Influencing Your Day": {"es": "Lo que influye en tu día", "pt-BR": "O que está influenciando seu dia"},
    "What's in a report?": {"es": "¿Qué hay en un reporte?", "pt-BR": "O que há em um relatório?"},
    "What's your concern?": {"es": "¿Cuál es tu preocupación?", "pt-BR": "Qual é sua preocupação?"},
    "When did this begin?": {"es": "¿Cuándo comenzó esto?", "pt-BR": "Quando isso começou?"},
    "When enabled, breathing exercises will automatically adjust their pace based on your real-time heart rate data from Apple Watch.": {"es": "Cuando está habilitado, los ejercicios de respiración ajustarán automáticamente su ritmo basándose en los datos de frecuencia cardíaca en tiempo real de tu Apple Watch.", "pt-BR": "Quando ativado, os exercícios de respiração ajustarão automaticamente seu ritmo com base nos dados de frequência cardíaca em tempo real do seu Apple Watch."},
    "When score drops": {"es": "Cuando la puntuación baja", "pt-BR": "Quando a pontuação cai"},
    "When you complete an exercise, we contribute:": {"es": "Cuando completas un ejercicio, contribuimos:", "pt-BR": "Quando você completa um exercício, contribuímos:"},
    "When you log a mood, we contribute:": {"es": "Cuando registras un estado de ánimo, contribuimos:", "pt-BR": "Quando você registra um humor, contribuímos:"},
    "When you progress in a pathway, we contribute:": {"es": "Cuando avanzas en un camino, contribuimos:", "pt-BR": "Quando você progride em um caminho, contribuímos:"},
    "White Noise": {"es": "Ruido blanco", "pt-BR": "Ruído branco"},
    "Why You Matched": {"es": "Por qué coincidiste", "pt-BR": "Por que você combinou"},
    "Why are you ending this mentorship?": {"es": "¿Por qué estás terminando esta mentoría?", "pt-BR": "Por que você está encerrando esta mentoria?"},
    "Why did I get this?": {"es": "¿Por qué recibí esto?", "pt-BR": "Por que recebi isso?"},
    "Wind-Down Duration": {"es": "Duración de relajación", "pt-BR": "Duração do relaxamento"},
    "Wind-Down Routine": {"es": "Rutina de relajación", "pt-BR": "Rotina de relaxamento"},
    "Withdrawals (%lld)": {"es": "Retiros (%lld)", "pt-BR": "Retiradas (%lld)"},
    "Woke up": {"es": "Despertó", "pt-BR": "Acordou"},
    "Writing Style": {"es": "Estilo de escritura", "pt-BR": "Estilo de escrita"},
    "Year": {"es": "Año", "pt-BR": "Ano"},
    "Year at a Glance": {"es": "Año de un vistazo", "pt-BR": "Ano de relance"},
    "Year-over-Year Comparison": {"es": "Comparación año tras año", "pt-BR": "Comparação ano a ano"},
    "Yearly Overview": {"es": "Resumen anual", "pt-BR": "Resumo anual"},
    "Yes, I'm ready": {"es": "Sí, estoy listo", "pt-BR": "Sim, estou pronto"},
    "You can adjust this anytime in Settings": {"es": "Puedes ajustar esto en cualquier momento en Configuración", "pt-BR": "Você pode ajustar isso a qualquer momento nas Configurações"},
    "You can return to '%@' anytime": {"es": "Puedes volver a '%@' en cualquier momento", "pt-BR": "Você pode voltar para '%@' a qualquer momento"},
    "You can still complete quests if you want": {"es": "Aún puedes completar misiones si quieres", "pt-BR": "Você ainda pode completar missões se quiser"},
    "You completed %lld breathing cycles": {"es": "Completaste %lld ciclos de respiración", "pt-BR": "Você completou %lld ciclos de respiração"},
    "You completed the %@": {"es": "Completaste el %@", "pt-BR": "Você completou o %@"},
    "You have completed the current phase. Double tap to begin the next phase of your journey.": {"es": "Has completado la fase actual. Toca dos veces para comenzar la siguiente fase de tu viaje.", "pt-BR": "Você completou a fase atual. Toque duas vezes para iniciar a próxima fase da sua jornada."},
    "You haven't favorited any exercises yet": {"es": "Aún no has marcado ningún ejercicio como favorito", "pt-BR": "Você ainda não favoritou nenhum exercício"},
    "You identified %lld things in your environment": {"es": "Identificaste %lld cosas en tu entorno", "pt-BR": "Você identificou %lld coisas em seu ambiente"},
    "You just experienced a significant emotional shift!": {"es": "¡Acabas de experimentar un cambio emocional significativo!", "pt-BR": "Você acabou de experimentar uma mudança emocional significativa!"},
    "You spent time immersed in nature": {"es": "Pasaste tiempo inmerso en la naturaleza", "pt-BR": "Você passou tempo imerso na natureza"},
    "You'll see suggestions for common thinking patterns.": {"es": "Verás sugerencias para patrones de pensamiento comunes.", "pt-BR": "Você verá sugestões para padrões de pensamento comuns."},
    "You'll see suggestions for subtle thinking patterns too.": {"es": "También verás sugerencias para patrones de pensamiento sutiles.", "pt-BR": "Você também verá sugestões para padrões de pensamento sutis."},
    "You'll see suggestions only for very clear thinking patterns.": {"es": "Verás sugerencias solo para patrones de pensamiento muy claros.", "pt-BR": "Você verá sugestões apenas para padrões de pensamento muito claros."},
    "You're Not Alone": {"es": "No estás solo", "pt-BR": "Você não está sozinho"},
    "You're grounded!": {"es": "¡Estás conectado a tierra!", "pt-BR": "Você está aterrado!"},
    "You're not alone. %@": {"es": "No estás solo. %@", "pt-BR": "Você não está sozinho. %@"},
    "You've Grown": {"es": "Has crecido", "pt-BR": "Você cresceu"},
    "You've completed this phase. Are you ready to move to the next stage of your journey?": {"es": "Has completado esta fase. ¿Estás listo para pasar a la siguiente etapa de tu viaje?", "pt-BR": "Você completou esta fase. Está pronto para passar para a próxima etapa da sua jornada?"},
    "You've completed your nature immersion journey": {"es": "Has completado tu viaje de inmersión en la naturaleza", "pt-BR": "Você completou sua jornada de imersão na natureza"},
    "You've created a sanctuary you can return to anytime": {"es": "Has creado un santuario al que puedes volver en cualquier momento", "pt-BR": "Você criou um santuário para o qual pode voltar a qualquer momento"},
    "You've placed %lld objects in your safe space.": {"es": "Has colocado %lld objetos en tu espacio seguro.", "pt-BR": "Você colocou %lld objetos em seu espaço seguro."},
    "You've unlocked new features": {"es": "Has desbloqueado nuevas funciones", "pt-BR": "Você desbloqueou novos recursos"},
    "Your Capacity": {"es": "Tu capacidad", "pt-BR": "Sua capacidade"},
    "Your Current Quest": {"es": "Tu misión actual", "pt-BR": "Sua missão atual"},
    "Your Emotional State": {"es": "Tu estado emocional", "pt-BR": "Seu estado emocional"},
    "Your Journey So Far": {"es": "Tu viaje hasta ahora", "pt-BR": "Sua jornada até agora"},
    "Your Journey Starts Here": {"es": "Tu viaje comienza aquí", "pt-BR": "Sua jornada começa aqui"},
    "Your Mentorship Status": {"es": "Tu estado de mentoría", "pt-BR": "Seu status de mentoria"},
    "Your Safe Space": {"es": "Tu espacio seguro", "pt-BR": "Seu espaço seguro"},
    "Your Signature (%lld)": {"es": "Tu firma (%lld)", "pt-BR": "Sua assinatura (%lld)"},
    "Your Strategy": {"es": "Tu estrategia", "pt-BR": "Sua estratégia"},
    "Your Thinking Patterns": {"es": "Tus patrones de pensamiento", "pt-BR": "Seus padrões de pensamento"},
    "Your Top 5 Values": {"es": "Tus 5 valores principales", "pt-BR": "Seus 5 principais valores"},
    "Your Values Compass": {"es": "Tu brújula de valores", "pt-BR": "Sua bússola de valores"},
    "Your baseline is calculated from the last 14 days of heart rate data. A reliable baseline needs at least 10 samples.": {"es": "Tu línea base se calcula a partir de los últimos 14 días de datos de frecuencia cardíaca. Una línea base confiable necesita al menos 10 muestras.", "pt-BR": "Sua linha de base é calculada a partir dos últimos 14 dias de dados de frequência cardíaca. Uma linha de base confiável precisa de pelo menos 10 amostras."},
    "Your best times for wellness moments:": {"es": "Tus mejores momentos para el bienestar:", "pt-BR": "Seus melhores momentos para o bem-estar:"},
    "Your data is hashed with SHA-256 encryption. We never store your user ID with contributions.": {"es": "Tus datos se cifran con SHA-256. Nunca almacenamos tu ID de usuario con las contribuciones.", "pt-BR": "Seus dados são criptografados com SHA-256. Nunca armazenamos seu ID de usuário com contribuições."},
    "Your device supports full AR experiences with real-world tracking.": {"es": "Tu dispositivo soporta experiencias de RA completas con seguimiento del mundo real.", "pt-BR": "Seu dispositivo suporta experiências de RA completas com rastreamento do mundo real."},
    "Your device will use non-AR fallback modes for grounding exercises. The experience is still effective, just without AR visuals.": {"es": "Tu dispositivo usará modos de respaldo sin RA para ejercicios de conexión a tierra. La experiencia sigue siendo efectiva, solo sin visuales de RA.", "pt-BR": "Seu dispositivo usará modos de fallback sem RA para exercícios de aterramento. A experiência ainda é eficaz, apenas sem visuais de RA."},
    "Your feedback helps us improve pattern detection": {"es": "Tu comentario nos ayuda a mejorar la detección de patrones", "pt-BR": "Seu feedback nos ajuda a melhorar a detecção de padrões"},
    "Your feedback helps us improve pattern detection. Your signature has been updated.": {"es": "Tu comentario nos ayuda a mejorar la detección de patrones. Tu firma ha sido actualizada.", "pt-BR": "Seu feedback nos ajuda a melhorar a detecção de padrões. Sua assinatura foi atualizada."},
    "Your feedback helps us improve predictions": {"es": "Tu comentario nos ayuda a mejorar las predicciones", "pt-BR": "Seu feedback nos ajuda a melhorar as previsões"},
    "Your first weekly story will appear after your first week of activity": {"es": "Tu primera historia semanal aparecerá después de tu primera semana de actividad", "pt-BR": "Sua primeira história semanal aparecerá após sua primeira semana de atividade"},
    "Your heart rate decreased by %lld BPM": {"es": "Tu frecuencia cardíaca disminuyó %lld PPM", "pt-BR": "Sua frequência cardíaca diminuiu %lld BPM"},
    "Your inquiry has been submitted. Our team will contact you within 24 hours.": {"es": "Tu consulta ha sido enviada. Nuestro equipo te contactará dentro de 24 horas.", "pt-BR": "Sua consulta foi enviada. Nossa equipe entrará em contato em até 24 horas."},
    "Your mood tends to be highest in %@ and lowest in %@": {"es": "Tu estado de ánimo tiende a ser más alto en %@ y más bajo en %@", "pt-BR": "Seu humor tende a ser mais alto em %@ e mais baixo em %@"},
    "Your progress will be saved.": {"es": "Tu progreso será guardado.", "pt-BR": "Seu progresso será salvo."},
    "Your report will include:": {"es": "Tu reporte incluirá:", "pt-BR": "Seu relatório incluirá:"},
    "Your safe space will not be saved.": {"es": "Tu espacio seguro no será guardado.", "pt-BR": "Seu espaço seguro não será salvo."},
    "Your strategy will be reviewed before publishing. Your identity is never attached.": {"es": "Tu estrategia será revisada antes de publicarse. Tu identidad nunca se adjunta.", "pt-BR": "Sua estratégia será revisada antes de ser publicada. Sua identidade nunca é anexada."},
    "Your streak is frozen for %lld days": {"es": "Tu racha está congelada por %lld días", "pt-BR": "Sua sequência está congelada por %lld dias"},
    "Your streak will be frozen during this period": {"es": "Tu racha será congelada durante este período", "pt-BR": "Sua sequência será congelada durante este período"},
    "Your streak won't be affected during vacation mode": {"es": "Tu racha no se verá afectada durante el modo vacaciones", "pt-BR": "Sua sequência não será afetada durante o modo férias"},
    "Your stress signature reveals %lld patterns from your wellness data.": {"es": "Tu firma de estrés revela %lld patrones de tus datos de bienestar.", "pt-BR": "Sua assinatura de estresse revela %lld padrões dos seus dados de bem-estar."},
}

def main():
    xcstrings_path = 'apps/ios/MindFriendApp/Resources/Localizable.xcstrings'
    with open(xcstrings_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    strings = data.get('strings', {})
    translated_count = 0
    
    for key, value in strings.items():
        if key in TRANSLATIONS:
            localizations = value.get('localizations', {})
            trans = TRANSLATIONS[key]
            
            if 'es' in trans:
                if 'es' not in localizations:
                    localizations['es'] = {}
                localizations['es']['stringUnit'] = {
                    'state': 'translated',
                    'value': trans['es']
                }
            
            if 'pt-BR' in trans:
                if 'pt-BR' not in localizations:
                    localizations['pt-BR'] = {}
                localizations['pt-BR']['stringUnit'] = {
                    'state': 'translated',
                    'value': trans['pt-BR']
                }
            
            value['localizations'] = localizations
            translated_count += 1
    
    with open(xcstrings_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Applied {translated_count} additional translations")
    
    missing_count = 0
    for key, value in strings.items():
        localizations = value.get('localizations', {})
        es_loc = localizations.get('es', {})
        es_unit = es_loc.get('stringUnit', {})
        if not es_unit.get('value'):
            missing_count += 1
    
    print(f"Still missing: {missing_count} strings")

if __name__ == '__main__':
    main()
