#!/usr/bin/env python3
"""
Translate remaining missing strings in Localizable.xcstrings - Batch 3 (Final)
"""
import json

# Final batch of translations
TRANSLATIONS = {
    # Special
    "''": {"es": "''", "pt-BR": "''"},
    
    # Assessment step prompts (these are placeholders that should be localized)
    "assessment.step1_description": {"es": "Paso 1 descripción", "pt-BR": "Descrição do passo 1"},
    "assessment.step1_prompt": {"es": "Pregunta del paso 1", "pt-BR": "Pergunta do passo 1"},
    "assessment.step2_description": {"es": "Paso 2 descripción", "pt-BR": "Descrição do passo 2"},
    "assessment.step2_prompt": {"es": "Pregunta del paso 2", "pt-BR": "Pergunta do passo 2"},
    "assessment.step3_description": {"es": "Paso 3 descripción", "pt-BR": "Descrição do passo 3"},
    "assessment.step3_prompt": {"es": "Pregunta del paso 3", "pt-BR": "Pergunta do passo 3"},
    "assessment.step4_description": {"es": "Paso 4 descripción", "pt-BR": "Descrição do passo 4"},
    "assessment.step4_prompt": {"es": "Pregunta del paso 4", "pt-BR": "Pergunta do passo 4"},
    
    # Double tap accessibility strings
    "Double tap for details": {"es": "Toca dos veces para ver detalles", "pt-BR": "Toque duas vezes para detalhes"},
    "Double tap for preparation tips": {"es": "Toca dos veces para consejos de preparación", "pt-BR": "Toque duas vezes para dicas de preparação"},
    "Double tap to %@ explanation": {"es": "Toca dos veces para %@ explicación", "pt-BR": "Toque duas vezes para %@ explicação"},
    "Double tap to create an AI-generated profile picture": {"es": "Toca dos veces para crear una foto de perfil generada con IA", "pt-BR": "Toque duas vezes para criar uma foto de perfil gerada por IA"},
    "Double tap to dismiss this thought pattern prompt": {"es": "Toca dos veces para descartar esta indicación de patrón de pensamiento", "pt-BR": "Toque duas vezes para dispensar este prompt de padrão de pensamento"},
    "Double tap to exit and save progress": {"es": "Toca dos veces para salir y guardar el progreso", "pt-BR": "Toque duas vezes para sair e salvar o progresso"},
    "Double tap to exit without saving": {"es": "Toca dos veces para salir sin guardar", "pt-BR": "Toque duas vezes para sair sem salvar"},
    "Double tap to generate a profile picture using AI": {"es": "Toca dos veces para generar una foto de perfil usando IA", "pt-BR": "Toque duas vezes para gerar uma foto de perfil usando IA"},
    "Double tap to open %@": {"es": "Toca dos veces para abrir %@", "pt-BR": "Toque duas vezes para abrir %@"},
    "Double tap to select a photo from your device": {"es": "Toca dos veces para seleccionar una foto de tu dispositivo", "pt-BR": "Toque duas vezes para selecionar uma foto do seu dispositivo"},
    "Double tap to start exercise": {"es": "Toca dos veces para iniciar el ejercicio", "pt-BR": "Toque duas vezes para iniciar o exercício"},
    "Double tap to view detailed capacity breakdown": {"es": "Toca dos veces para ver el desglose detallado de capacidad", "pt-BR": "Toque duas vezes para ver o detalhamento detalhado de capacidade"},
    "Double tap to view emotion details": {"es": "Toca dos veces para ver detalles de emociones", "pt-BR": "Toque duas vezes para ver detalhes de emoções"},
    "Double tap to view pathway details": {"es": "Toca dos veces para ver detalles del camino", "pt-BR": "Toque duas vezes para ver detalhes do caminho"},
    
    # E
    "e.g., Family vacation, work trip": {"es": "ej., Vacaciones familiares, viaje de trabajo", "pt-BR": "ex., Férias em família, viagem de trabalho"},
    
    # Followup keys
    "followup.error_title": {"es": "Error de seguimiento", "pt-BR": "Erro de acompanhamento"},
    "followup.next_action_footer": {"es": "Pie de página de próxima acción", "pt-BR": "Rodapé da próxima ação"},
    "followup.next_action_header": {"es": "Próxima acción", "pt-BR": "Próxima ação"},
    "followup.next_action_placeholder": {"es": "Describe tu próxima acción...", "pt-BR": "Descreva sua próxima ação..."},
    "followup.notes_footer": {"es": "Pie de página de notas", "pt-BR": "Rodapé de notas"},
    "followup.notes_header": {"es": "Notas", "pt-BR": "Notas"},
    "followup.notes_placeholder": {"es": "Agrega notas adicionales...", "pt-BR": "Adicione notas adicionais..."},
    "followup.outcome_challenged": {"es": "Desafiado", "pt-BR": "Desafiado"},
    "followup.outcome_challenged_description": {"es": "El límite fue cuestionado", "pt-BR": "O limite foi questionado"},
    "followup.outcome_header": {"es": "Resultado", "pt-BR": "Resultado"},
    "followup.outcome_ignored": {"es": "Ignorado", "pt-BR": "Ignorado"},
    "followup.outcome_ignored_description": {"es": "El límite fue ignorado", "pt-BR": "O limite foi ignorado"},
    "followup.outcome_label": {"es": "Resultado", "pt-BR": "Resultado"},
    "followup.outcome_partially_successful": {"es": "Parcialmente exitoso", "pt-BR": "Parcialmente bem-sucedido"},
    "followup.outcome_partially_successful_description": {"es": "El límite fue parcialmente respetado", "pt-BR": "O limite foi parcialmente respeitado"},
    "followup.outcome_successful": {"es": "Exitoso", "pt-BR": "Bem-sucedido"},
    "followup.outcome_successful_description": {"es": "El límite fue respetado completamente", "pt-BR": "O limite foi completamente respeitado"},
    "followup.recording": {"es": "Grabando", "pt-BR": "Gravando"},
    "followup.reflection_footer": {"es": "Pie de página de reflexión", "pt-BR": "Rodapé de reflexão"},
    "followup.reflection_header": {"es": "Reflexión", "pt-BR": "Reflexão"},
    "followup.reflection_placeholder": {"es": "Reflexiona sobre esta experiencia...", "pt-BR": "Reflita sobre esta experiência..."},
    "followup.submit": {"es": "Enviar", "pt-BR": "Enviar"},
    "followup.success_title": {"es": "Seguimiento guardado", "pt-BR": "Acompanhamento salvo"},
    "followup.suggestions_header": {"es": "Sugerencias", "pt-BR": "Sugestões"},
    "followup.title": {"es": "Seguimiento", "pt-BR": "Acompanhamento"},
    
    # H
    "How well your signature predicts crises": {"es": "Qué tan bien tu firma predice crisis", "pt-BR": "Quão bem sua assinatura prevê crises"},
    
    # List keys
    "list.button_new": {"es": "Nuevo", "pt-BR": "Novo"},
    "list.empty_state": {"es": "No hay elementos", "pt-BR": "Nenhum item"},
    "list.filter_active": {"es": "Activo", "pt-BR": "Ativo"},
    "list.filter_all": {"es": "Todos", "pt-BR": "Todos"},
    "list.has_followup": {"es": "Tiene seguimiento", "pt-BR": "Tem acompanhamento"},
    "list.title": {"es": "Lista", "pt-BR": "Lista"},
    
    # M
    "ML Timing Insights": {"es": "Perspectivas de tiempo con ML", "pt-BR": "Insights de tempo com ML"},
    "Manage Patterns": {"es": "Gestionar patrones", "pt-BR": "Gerenciar padrões"},
    "Manage excluded patterns": {"es": "Gestionar patrones excluidos", "pt-BR": "Gerenciar padrões excluídos"},
    "Manual Override": {"es": "Anulación manual", "pt-BR": "Substituição manual"},
    "Manual Themes": {"es": "Temas manuales", "pt-BR": "Temas manuais"},
    "Manual override": {"es": "Anulación manual", "pt-BR": "Substituição manual"},
    "Manual override active": {"es": "Anulación manual activa", "pt-BR": "Substituição manual ativa"},
    "Manually adjust today's difficulty level. Resets at midnight.": {"es": "Ajusta manualmente el nivel de dificultad de hoy. Se reinicia a medianoche.", "pt-BR": "Ajuste manualmente o nível de dificuldade de hoje. Reinicia à meia-noite."},
    "Mark as helpful": {"es": "Marcar como útil", "pt-BR": "Marcar como útil"},
    "Mark as not helpful": {"es": "Marcar como no útil", "pt-BR": "Marcar como não útil"},
    "Max %lld Interventions/Day": {"es": "Máximo %lld intervenciones/día", "pt-BR": "Máximo %lld intervenções/dia"},
    "Meditation Settings": {"es": "Configuración de meditación", "pt-BR": "Configurações de meditação"},
    "Mentor": {"es": "Mentor", "pt-BR": "Mentor"},
    "Mentor Bio": {"es": "Biografía del mentor", "pt-BR": "Biografia do mentor"},
    "Mentor Profile": {"es": "Perfil de mentor", "pt-BR": "Perfil de mentor"},
    "Mentee": {"es": "Aprendiz", "pt-BR": "Mentorado"},
    "Message": {"es": "Mensaje", "pt-BR": "Mensagem"},
    "Message %@": {"es": "Mensaje %@", "pt-BR": "Mensagem %@"},
    "Message Content": {"es": "Contenido del mensaje", "pt-BR": "Conteúdo da mensagem"},
    "Message Preview": {"es": "Vista previa del mensaje", "pt-BR": "Visualização da mensagem"},
    "Middle": {"es": "Medio", "pt-BR": "Meio"},
    "Minimal": {"es": "Mínimo", "pt-BR": "Mínimo"},
    "Minimize Coaching": {"es": "Minimizar coaching", "pt-BR": "Minimizar coaching"},
    "Minimum Score: %lld": {"es": "Puntuación mínima: %lld", "pt-BR": "Pontuação mínima: %lld"},
    "Minutes until next phase": {"es": "Minutos hasta la próxima fase", "pt-BR": "Minutos até a próxima fase"},
    "Mode": {"es": "Modo", "pt-BR": "Modo"},
    "Model": {"es": "Modelo", "pt-BR": "Modelo"},
    "Moderate": {"es": "Moderado", "pt-BR": "Moderado"},
    "Mood Score: %lld/10": {"es": "Puntuación de ánimo: %lld/10", "pt-BR": "Pontuação de humor: %lld/10"},
    "Mood Trend: %@": {"es": "Tendencia de ánimo: %@", "pt-BR": "Tendência de humor: %@"},
    "More Alerts": {"es": "Más alertas", "pt-BR": "Mais alertas"},
    "More Options": {"es": "Más opciones", "pt-BR": "Mais opções"},
    "Morning": {"es": "Mañana", "pt-BR": "Manhã"},
    "Most effective: %@": {"es": "Más efectivo: %@", "pt-BR": "Mais eficaz: %@"},
    "Most used:": {"es": "Más usado:", "pt-BR": "Mais usado:"},
    "Move to: %@": {"es": "Mover a: %@", "pt-BR": "Mover para: %@"},
    "Music": {"es": "Música", "pt-BR": "Música"},
    "My Exercises": {"es": "Mis ejercicios", "pt-BR": "Meus exercícios"},
    "My Mentorships": {"es": "Mis mentorías", "pt-BR": "Minhas mentorias"},
    "My Pathways": {"es": "Mis caminos", "pt-BR": "Meus caminhos"},
    "My Reports": {"es": "Mis reportes", "pt-BR": "Meus relatórios"},
    "My Safe Spaces": {"es": "Mis espacios seguros", "pt-BR": "Meus espaços seguros"},
    
    # N
    "Name error: %@": {"es": "Error de nombre: %@", "pt-BR": "Erro de nome: %@"},
    "Nature Connection": {"es": "Conexión con la naturaleza", "pt-BR": "Conexão com a natureza"},
    "Net Balance": {"es": "Balance neto", "pt-BR": "Saldo líquido"},
    "Next: %@": {"es": "Siguiente: %@", "pt-BR": "Próximo: %@"},
    "No": {"es": "No", "pt-BR": "Não"},
    "No Actions Yet": {"es": "Aún no hay acciones", "pt-BR": "Nenhuma ação ainda"},
    "No Debt Data Yet": {"es": "Aún no hay datos de deuda", "pt-BR": "Nenhum dado de dívida ainda"},
    "No Exercises Available": {"es": "No hay ejercicios disponibles", "pt-BR": "Nenhum exercício disponível"},
    "No Favorite Stories": {"es": "No hay historias favoritas", "pt-BR": "Nenhuma história favorita"},
    "No Matches Yet": {"es": "Aún no hay coincidencias", "pt-BR": "Nenhuma combinação ainda"},
    "No Mentorships Yet": {"es": "Aún no hay mentorías", "pt-BR": "Nenhuma mentoria ainda"},
    "No Past Mentorships": {"es": "No hay mentorías pasadas", "pt-BR": "Nenhuma mentoria passada"},
    "No Pattern Data": {"es": "No hay datos de patrones", "pt-BR": "Nenhum dado de padrão"},
    "No Pending Requests": {"es": "No hay solicitudes pendientes", "pt-BR": "Nenhuma solicitação pendente"},
    "No Recent Actions": {"es": "No hay acciones recientes", "pt-BR": "Nenhuma ação recente"},
    "No Recent Alerts": {"es": "No hay alertas recientes", "pt-BR": "Nenhum alerta recente"},
    "No Reports Yet": {"es": "Aún no hay reportes", "pt-BR": "Nenhum relatório ainda"},
    "No Results": {"es": "Sin resultados", "pt-BR": "Sem resultados"},
    "No Safe Spaces": {"es": "No hay espacios seguros", "pt-BR": "Nenhum espaço seguro"},
    "No Saved Exercises": {"es": "No hay ejercicios guardados", "pt-BR": "Nenhum exercício salvo"},
    "No Saved Spaces": {"es": "No hay espacios guardados", "pt-BR": "Nenhum espaço salvo"},
    "No Stories Yet": {"es": "Aún no hay historias", "pt-BR": "Nenhuma história ainda"},
    "No active interventions": {"es": "No hay intervenciones activas", "pt-BR": "Nenhuma intervenção ativa"},
    "No alerts from this week": {"es": "No hay alertas de esta semana", "pt-BR": "Nenhum alerta desta semana"},
    "No assessments due": {"es": "No hay evaluaciones pendientes", "pt-BR": "Nenhuma avaliação pendente"},
    "No audio tracks available": {"es": "No hay pistas de audio disponibles", "pt-BR": "Nenhuma faixa de áudio disponível"},
    "No certificates earned yet": {"es": "Aún no hay certificados obtenidos", "pt-BR": "Nenhum certificado conquistado ainda"},
    "No challenges": {"es": "No hay desafíos", "pt-BR": "Nenhum desafio"},
    "No circles yet": {"es": "Aún no hay círculos", "pt-BR": "Nenhum círculo ainda"},
    "No content available": {"es": "No hay contenido disponible", "pt-BR": "Nenhum conteúdo disponível"},
    "No entries yet": {"es": "Aún no hay entradas", "pt-BR": "Nenhuma entrada ainda"},
    "No events logged": {"es": "No hay eventos registrados", "pt-BR": "Nenhum evento registrado"},
    "No exercises generated yet": {"es": "Aún no hay ejercicios generados", "pt-BR": "Nenhum exercício gerado ainda"},
    "No favorites yet": {"es": "Aún no hay favoritos", "pt-BR": "Nenhum favorito ainda"},
    "No goals set yet": {"es": "Aún no hay metas establecidas", "pt-BR": "Nenhuma meta definida ainda"},
    "No history yet": {"es": "Aún no hay historial", "pt-BR": "Nenhum histórico ainda"},
    "No insights available": {"es": "No hay perspectivas disponibles", "pt-BR": "Nenhum insight disponível"},
    "No mentors found matching your criteria": {"es": "No se encontraron mentores que coincidan con tus criterios", "pt-BR": "Nenhum mentor encontrado correspondendo aos seus critérios"},
    "No messages yet": {"es": "Aún no hay mensajes", "pt-BR": "Nenhuma mensagem ainda"},
    "No moods logged yet": {"es": "Aún no hay estados de ánimo registrados", "pt-BR": "Nenhum humor registrado ainda"},
    "No patterns detected yet": {"es": "Aún no hay patrones detectados", "pt-BR": "Nenhum padrão detectado ainda"},
    "No posts yet": {"es": "Aún no hay publicaciones", "pt-BR": "Nenhuma publicação ainda"},
    "No prediction available": {"es": "No hay predicción disponible", "pt-BR": "Nenhuma previsão disponível"},
    "No previous assessments": {"es": "No hay evaluaciones anteriores", "pt-BR": "Nenhuma avaliação anterior"},
    "No recent interventions": {"es": "No hay intervenciones recientes", "pt-BR": "Nenhuma intervenção recente"},
    "No recent moods logged": {"es": "No hay estados de ánimo recientes registrados", "pt-BR": "Nenhum humor recente registrado"},
    "No recordings yet": {"es": "Aún no hay grabaciones", "pt-BR": "Nenhuma gravação ainda"},
    "No results found": {"es": "No se encontraron resultados", "pt-BR": "Nenhum resultado encontrado"},
    "No sessions yet": {"es": "Aún no hay sesiones", "pt-BR": "Nenhuma sessão ainda"},
    "No sleep data available": {"es": "No hay datos de sueño disponibles", "pt-BR": "Nenhum dado de sono disponível"},
    "No stories this week": {"es": "No hay historias esta semana", "pt-BR": "Nenhuma história esta semana"},
    "No strategies found": {"es": "No se encontraron estrategias", "pt-BR": "Nenhuma estratégia encontrada"},
    "No transactions yet": {"es": "Aún no hay transacciones", "pt-BR": "Nenhuma transação ainda"},
    "No trends detected yet": {"es": "Aún no hay tendencias detectadas", "pt-BR": "Nenhuma tendência detectada ainda"},
    "Not Authorized": {"es": "No autorizado", "pt-BR": "Não autorizado"},
    "Not Determined": {"es": "No determinado", "pt-BR": "Não determinado"},
    "Not now": {"es": "Ahora no", "pt-BR": "Agora não"},
    "Nothing to Analyze Yet": {"es": "Nada que analizar aún", "pt-BR": "Nada para analisar ainda"},
    "Notice any thoughts, feelings, or sensations": {"es": "Nota cualquier pensamiento, sentimiento o sensación", "pt-BR": "Note quaisquer pensamentos, sentimentos ou sensações"},
    "Notification Preferences": {"es": "Preferencias de notificación", "pt-BR": "Preferências de notificação"},
    "Now": {"es": "Ahora", "pt-BR": "Agora"},
    
    # O
    "Objective: %@": {"es": "Objetivo: %@", "pt-BR": "Objetivo: %@"},
    "Ongoing": {"es": "En curso", "pt-BR": "Em andamento"},
    "Open immersive augmented reality grounding exercises": {"es": "Abrir ejercicios inmersivos de conexión a tierra con realidad aumentada", "pt-BR": "Abrir exercícios imersivos de aterramento com realidade aumentada"},
    "Optional message about your team's mental health needs": {"es": "Mensaje opcional sobre las necesidades de salud mental de tu equipo", "pt-BR": "Mensagem opcional sobre as necessidades de saúde mental da sua equipe"},
    "Or try these:": {"es": "O prueba estos:", "pt-BR": "Ou tente estes:"},
    "Original": {"es": "Original", "pt-BR": "Original"},
    "Override active until midnight": {"es": "Anulación activa hasta medianoche", "pt-BR": "Substituição ativa até meia-noite"},
    
    # P
    "PRO": {"es": "PRO", "pt-BR": "PRO"},
    "Pace adapts to your heart rate": {"es": "El ritmo se adapta a tu frecuencia cardíaca", "pt-BR": "O ritmo se adapta à sua frequência cardíaca"},
    "Past Mentorships": {"es": "Mentorías pasadas", "pt-BR": "Mentorias passadas"},
    "Pathway Progress": {"es": "Progreso del camino", "pt-BR": "Progresso do caminho"},
    "Pattern Confidence": {"es": "Confianza del patrón", "pt-BR": "Confiança do padrão"},
    "Pattern Distribution": {"es": "Distribución de patrones", "pt-BR": "Distribuição de padrões"},
    "Pattern Emerging": {"es": "Patrón emergente", "pt-BR": "Padrão emergente"},
    "Pattern type: %@": {"es": "Tipo de patrón: %@", "pt-BR": "Tipo de padrão: %@"},
    "Pause exercise": {"es": "Pausar ejercicio", "pt-BR": "Pausar exercício"},
    "Peak times:": {"es": "Horas pico:", "pt-BR": "Horários de pico:"},
    "Pending": {"es": "Pendiente", "pt-BR": "Pendente"},
    "Pending Approval": {"es": "Aprobación pendiente", "pt-BR": "Aprovação pendente"},
    "Pending Invites": {"es": "Invitaciones pendientes", "pt-BR": "Convites pendentes"},
    "Pending Requests": {"es": "Solicitudes pendientes", "pt-BR": "Solicitações pendentes"},
    "Personal Message (Optional)": {"es": "Mensaje personal (opcional)", "pt-BR": "Mensagem pessoal (opcional)"},
    "Personal Note": {"es": "Nota personal", "pt-BR": "Nota pessoal"},
    "Personalization": {"es": "Personalización", "pt-BR": "Personalização"},
    "Phase %lld": {"es": "Fase %lld", "pt-BR": "Fase %lld"},
    "Phase %lld of %lld": {"es": "Fase %lld de %lld", "pt-BR": "Fase %lld de %lld"},
    "Phase Complete": {"es": "Fase completada", "pt-BR": "Fase completa"},
    "Phase Complete!": {"es": "¡Fase completada!", "pt-BR": "Fase completa!"},
    "Phase complete!": {"es": "¡Fase completada!", "pt-BR": "Fase completa!"},
    "Pick a voice for AI-generated content": {"es": "Elige una voz para el contenido generado por IA", "pt-BR": "Escolha uma voz para o conteúdo gerado por IA"},
    "Place Mode": {"es": "Modo de colocación", "pt-BR": "Modo de posicionamento"},
    "Place objects in the environment": {"es": "Coloca objetos en el entorno", "pt-BR": "Coloque objetos no ambiente"},
    "Placed Objects": {"es": "Objetos colocados", "pt-BR": "Objetos colocados"},
    "Placing...": {"es": "Colocando...", "pt-BR": "Colocando..."},
    "Plan Created": {"es": "Plan creado", "pt-BR": "Plano criado"},
    "Plan Name": {"es": "Nombre del plan", "pt-BR": "Nome do plano"},
    "Play": {"es": "Reproducir", "pt-BR": "Reproduzir"},
    "Play Sample": {"es": "Reproducir muestra", "pt-BR": "Reproduzir amostra"},
    "Please complete HealthKit setup first": {"es": "Por favor completa la configuración de HealthKit primero", "pt-BR": "Por favor complete a configuração do HealthKit primeiro"},
    "Please enter a prompt": {"es": "Por favor ingresa una indicación", "pt-BR": "Por favor digite um prompt"},
    "Please enter your email": {"es": "Por favor ingresa tu correo electrónico", "pt-BR": "Por favor digite seu email"},
    "Please rate this exercise": {"es": "Por favor califica este ejercicio", "pt-BR": "Por favor avalie este exercício"},
    "Please try again": {"es": "Por favor intenta de nuevo", "pt-BR": "Por favor tente novamente"},
    "Poor": {"es": "Pobre", "pt-BR": "Ruim"},
    "Post": {"es": "Publicar", "pt-BR": "Publicar"},
    "Post Check-In": {"es": "Publicar registro", "pt-BR": "Publicar check-in"},
    "Post-Exercise Reflection": {"es": "Reflexión post-ejercicio", "pt-BR": "Reflexão pós-exercício"},
    "Practice": {"es": "Práctica", "pt-BR": "Prática"},
    "Practice Mode": {"es": "Modo de práctica", "pt-BR": "Modo de prática"},
    "Prediction Accuracy": {"es": "Precisión de predicción", "pt-BR": "Precisão de previsão"},
    "Prediction Confidence": {"es": "Confianza de predicción", "pt-BR": "Confiança de previsão"},
    "Prediction Model": {"es": "Modelo de predicción", "pt-BR": "Modelo de previsão"},
    "Preferred Voice": {"es": "Voz preferida", "pt-BR": "Voz preferida"},
    "Premium Feature": {"es": "Función premium", "pt-BR": "Recurso premium"},
    "Premium Features": {"es": "Funciones premium", "pt-BR": "Recursos premium"},
    "Premium Only": {"es": "Solo premium", "pt-BR": "Apenas premium"},
    "Premium Required": {"es": "Se requiere premium", "pt-BR": "Premium necessário"},
    "Premium subscription": {"es": "Suscripción premium", "pt-BR": "Assinatura premium"},
    "Premium unlocks unlimited access": {"es": "Premium desbloquea acceso ilimitado", "pt-BR": "Premium desbloqueia acesso ilimitado"},
    "Prepare": {"es": "Preparar", "pt-BR": "Preparar"},
    "Preparing exercise...": {"es": "Preparando ejercicio...", "pt-BR": "Preparando exercício..."},
    "Preparing your session...": {"es": "Preparando tu sesión...", "pt-BR": "Preparando sua sessão..."},
    "Press and hold to record": {"es": "Mantén presionado para grabar", "pt-BR": "Pressione e segure para gravar"},
    "Preview Sample": {"es": "Vista previa de muestra", "pt-BR": "Visualização de amostra"},
    "Previous": {"es": "Anterior", "pt-BR": "Anterior"},
    "Previous Phase": {"es": "Fase anterior", "pt-BR": "Fase anterior"},
    "Previous assessments": {"es": "Evaluaciones anteriores", "pt-BR": "Avaliações anteriores"},
    "Price": {"es": "Precio", "pt-BR": "Preço"},
    "Primary Emotion": {"es": "Emoción primaria", "pt-BR": "Emoção primária"},
    "Privacy & Data": {"es": "Privacidad y datos", "pt-BR": "Privacidade e dados"},
    "Privacy Settings": {"es": "Configuración de privacidad", "pt-BR": "Configurações de privacidade"},
    "Private": {"es": "Privado", "pt-BR": "Privado"},
    "Processing...": {"es": "Procesando...", "pt-BR": "Processando..."},
    "Profile Settings": {"es": "Configuración de perfil", "pt-BR": "Configurações de perfil"},
    "Profile Updated": {"es": "Perfil actualizado", "pt-BR": "Perfil atualizado"},
    "Program Complete": {"es": "Programa completado", "pt-BR": "Programa completo"},
    "Program Details": {"es": "Detalles del programa", "pt-BR": "Detalhes do programa"},
    "Progress": {"es": "Progreso", "pt-BR": "Progresso"},
    "Progress Report": {"es": "Reporte de progreso", "pt-BR": "Relatório de progresso"},
    "Progress Saved": {"es": "Progreso guardado", "pt-BR": "Progresso salvo"},
    "Prompt": {"es": "Indicación", "pt-BR": "Prompt"},
    "Protect your data with biometric authentication": {"es": "Protege tus datos con autenticación biométrica", "pt-BR": "Proteja seus dados com autenticação biométrica"},
    "Provides real-time heartbeat data for adaptive breathing": {"es": "Proporciona datos de latidos en tiempo real para respiración adaptativa", "pt-BR": "Fornece dados de batimentos em tempo real para respiração adaptativa"},
    "Public": {"es": "Público", "pt-BR": "Público"},
    "Push Notifications": {"es": "Notificaciones push", "pt-BR": "Notificações push"},
    
    # Q
    "Q%lld": {"es": "T%lld", "pt-BR": "T%lld"},
    "Quarter": {"es": "Trimestre", "pt-BR": "Trimestre"},
    "Quarterly Mood": {"es": "Ánimo trimestral", "pt-BR": "Humor trimestral"},
    "Quest Streak": {"es": "Racha de misiones", "pt-BR": "Sequência de missões"},
    "Questions to consider:": {"es": "Preguntas a considerar:", "pt-BR": "Perguntas a considerar:"},
    "Quick Generate": {"es": "Generación rápida", "pt-BR": "Geração rápida"},
    "Quota status": {"es": "Estado de cuota", "pt-BR": "Status de cota"},
    
    # R
    "Range": {"es": "Rango", "pt-BR": "Intervalo"},
    "Rank your top 5 values": {"es": "Clasifica tus 5 valores principales", "pt-BR": "Classifique seus 5 principais valores"},
    "Rate Sleep": {"es": "Calificar sueño", "pt-BR": "Avaliar sono"},
    "Rate Your Sleep": {"es": "Califica tu sueño", "pt-BR": "Avalie seu sono"},
    "Re-Learn from History": {"es": "Volver a aprender del historial", "pt-BR": "Reaprender do histórico"},
    "Ready to advance?": {"es": "¿Listo para avanzar?", "pt-BR": "Pronto para avançar?"},
    "Reason": {"es": "Razón", "pt-BR": "Motivo"},
    "Reason (Optional)": {"es": "Razón (opcional)", "pt-BR": "Motivo (opcional)"},
    "Recalculate Baseline": {"es": "Recalcular línea base", "pt-BR": "Recalcular linha de base"},
    "Receive": {"es": "Recibir", "pt-BR": "Receber"},
    "Recent": {"es": "Reciente", "pt-BR": "Recente"},
    "Recent Activity": {"es": "Actividad reciente", "pt-BR": "Atividade recente"},
    "Recent Alerts": {"es": "Alertas recientes", "pt-BR": "Alertas recentes"},
    "Recent Check-Ins": {"es": "Registros recientes", "pt-BR": "Check-ins recentes"},
    "Recent Exercises": {"es": "Ejercicios recientes", "pt-BR": "Exercícios recentes"},
    "Recent History": {"es": "Historial reciente", "pt-BR": "Histórico recente"},
    "Recent Interventions": {"es": "Intervenciones recientes", "pt-BR": "Intervenções recentes"},
    "Recent Patterns": {"es": "Patrones recientes", "pt-BR": "Padrões recentes"},
    "Recent Sessions": {"es": "Sesiones recientes", "pt-BR": "Sessões recentes"},
    "Recently Played": {"es": "Reproducido recientemente", "pt-BR": "Reproduzido recentemente"},
    "Recipient Email": {"es": "Correo del destinatario", "pt-BR": "Email do destinatário"},
    "Recording...": {"es": "Grabando...", "pt-BR": "Gravando..."},
    "Recovery Options": {"es": "Opciones de recuperación", "pt-BR": "Opções de recuperação"},
    "Recovery Plan": {"es": "Plan de recuperación", "pt-BR": "Plano de recuperação"},
    "Recovery Program": {"es": "Programa de recuperación", "pt-BR": "Programa de recuperação"},
    "Reduce Motion": {"es": "Reducir movimiento", "pt-BR": "Reduzir movimento"},
    "Refresh Matches": {"es": "Actualizar coincidencias", "pt-BR": "Atualizar combinações"},
    "Regenerate": {"es": "Regenerar", "pt-BR": "Regenerar"},
    "Rejected": {"es": "Rechazado", "pt-BR": "Rejeitado"},
    "Related Patterns": {"es": "Patrones relacionados", "pt-BR": "Padrões relacionados"},
    "Relationship Type": {"es": "Tipo de relación", "pt-BR": "Tipo de relacionamento"},
    "Relax and unwind": {"es": "Relájate y descansa", "pt-BR": "Relaxe e descanse"},
    "Relaxation Exercise": {"es": "Ejercicio de relajación", "pt-BR": "Exercício de relaxamento"},
    "Release to send": {"es": "Suelta para enviar", "pt-BR": "Solte para enviar"},
    "Remind Me": {"es": "Recordármelo", "pt-BR": "Lembrar-me"},
    "Reminder Time": {"es": "Hora del recordatorio", "pt-BR": "Hora do lembrete"},
    "Reminders": {"es": "Recordatorios", "pt-BR": "Lembretes"},
    "Remote": {"es": "Remoto", "pt-BR": "Remoto"},
    "Remove": {"es": "Eliminar", "pt-BR": "Remover"},
    "Remove Favorite": {"es": "Eliminar de favoritos", "pt-BR": "Remover dos favoritos"},
    "Remove from Favorites": {"es": "Eliminar de favoritos", "pt-BR": "Remover dos favoritos"},
    "Repeat": {"es": "Repetir", "pt-BR": "Repetir"},
    "Report": {"es": "Reportar", "pt-BR": "Denunciar"},
    "Report Generated": {"es": "Reporte generado", "pt-BR": "Relatório gerado"},
    "Report Issue": {"es": "Reportar problema", "pt-BR": "Reportar problema"},
    "Report Type": {"es": "Tipo de reporte", "pt-BR": "Tipo de relatório"},
    "Request": {"es": "Solicitar", "pt-BR": "Solicitar"},
    "Request Denied": {"es": "Solicitud denegada", "pt-BR": "Solicitação negada"},
    "Request Pending": {"es": "Solicitud pendiente", "pt-BR": "Solicitação pendente"},
    "Request Sent": {"es": "Solicitud enviada", "pt-BR": "Solicitação enviada"},
    "Request Support": {"es": "Solicitar apoyo", "pt-BR": "Solicitar apoio"},
    "Requested": {"es": "Solicitado", "pt-BR": "Solicitado"},
    "Required": {"es": "Requerido", "pt-BR": "Obrigatório"},
    "Reset": {"es": "Restablecer", "pt-BR": "Redefinir"},
    "Reset All": {"es": "Restablecer todo", "pt-BR": "Redefinir tudo"},
    "Reset Data": {"es": "Restablecer datos", "pt-BR": "Redefinir dados"},
    "Reset Preferences": {"es": "Restablecer preferencias", "pt-BR": "Redefinir preferências"},
    "Reset Signature": {"es": "Restablecer firma", "pt-BR": "Redefinir assinatura"},
    "Respond to the AI's questions to personalize your experience": {"es": "Responde a las preguntas de la IA para personalizar tu experiencia", "pt-BR": "Responda às perguntas da IA para personalizar sua experiência"},
    "Response Rate": {"es": "Tasa de respuesta", "pt-BR": "Taxa de resposta"},
    "Responses": {"es": "Respuestas", "pt-BR": "Respostas"},
    "Restart": {"es": "Reiniciar", "pt-BR": "Reiniciar"},
    "Restart Exercise": {"es": "Reiniciar ejercicio", "pt-BR": "Reiniciar exercício"},
    "Restart Session": {"es": "Reiniciar sesión", "pt-BR": "Reiniciar sessão"},
    "Results": {"es": "Resultados", "pt-BR": "Resultados"},
    "Resume": {"es": "Reanudar", "pt-BR": "Retomar"},
    "Resume Pathway": {"es": "Reanudar camino", "pt-BR": "Retomar caminho"},
    "Resume Session": {"es": "Reanudar sesión", "pt-BR": "Retomar sessão"},
    "Retrieve": {"es": "Recuperar", "pt-BR": "Recuperar"},
    "Review": {"es": "Revisar", "pt-BR": "Revisar"},
    "Review Request": {"es": "Revisar solicitud", "pt-BR": "Revisar solicitação"},
    "Rewrite Feedback": {"es": "Comentarios de reescritura", "pt-BR": "Feedback de reescrita"},
    "Risk Level": {"es": "Nivel de riesgo", "pt-BR": "Nível de risco"},
    "Ritual": {"es": "Ritual", "pt-BR": "Ritual"},
    "Rituals": {"es": "Rituales", "pt-BR": "Rituais"},
    "Role": {"es": "Rol", "pt-BR": "Função"},
    "Routine": {"es": "Rutina", "pt-BR": "Rotina"},
    "Routine Complete": {"es": "Rutina completada", "pt-BR": "Rotina completa"},
    "Run Baseline": {"es": "Ejecutar línea base", "pt-BR": "Executar linha de base"},
    
    # Definition keys
    "definition.error_title": {"es": "Error de definición", "pt-BR": "Erro de definição"},
    "definition.generate": {"es": "Generar", "pt-BR": "Gerar"},
    "definition.stakeholder_footer": {"es": "Pie de página del interesado", "pt-BR": "Rodapé do interessado"},
    "definition.stakeholder_header": {"es": "Persona involucrada", "pt-BR": "Pessoa envolvida"},
    "definition.stakeholder_placeholder": {"es": "Ingresa el nombre de la persona...", "pt-BR": "Digite o nome da pessoa..."},
    "definition.statement_footer": {"es": "Pie de página de la declaración", "pt-BR": "Rodapé da declaração"},
    "definition.statement_header": {"es": "Declaración de límite", "pt-BR": "Declaração de limite"},
    "definition.statement_placeholder": {"es": "Describe tu límite...", "pt-BR": "Descreva seu limite..."},
    "definition.templates_header": {"es": "Plantillas", "pt-BR": "Modelos"},
    "definition.title": {"es": "Definición", "pt-BR": "Definição"},
    "definition.type_digital": {"es": "Digital", "pt-BR": "Digital"},
    "definition.type_digital_description": {"es": "Límites relacionados con tecnología y tiempo de pantalla", "pt-BR": "Limites relacionados a tecnologia e tempo de tela"},
    "definition.type_emotional": {"es": "Emocional", "pt-BR": "Emocional"},
    "definition.type_emotional_description": {"es": "Límites relacionados con emociones y energía emocional", "pt-BR": "Limites relacionados a emoções e energia emocional"},
    "definition.type_financial": {"es": "Financiero", "pt-BR": "Financeiro"},
    "definition.type_financial_description": {"es": "Límites relacionados con dinero y recursos financieros", "pt-BR": "Limites relacionados a dinheiro e recursos financeiros"},
    "definition.type_header": {"es": "Tipo de límite", "pt-BR": "Tipo de limite"},
    "definition.type_label": {"es": "Tipo", "pt-BR": "Tipo"},
    "definition.type_physical": {"es": "Físico", "pt-BR": "Físico"},
    "definition.type_physical_description": {"es": "Límites relacionados con espacio personal y contacto físico", "pt-BR": "Limites relacionados a espaço pessoal e contato físico"},
    "definition.type_time": {"es": "Tiempo", "pt-BR": "Tempo"},
    "definition.type_time_description": {"es": "Límites relacionados con disponibilidad y horarios", "pt-BR": "Limites relacionados a disponibilidade e horários"},
    "definition.why_matters_footer": {"es": "Pie de página de por qué importa", "pt-BR": "Rodapé de por que importa"},
    "definition.why_matters_header": {"es": "Por qué importa", "pt-BR": "Por que importa"},
    "definition.why_matters_placeholder": {"es": "Explica por qué este límite es importante para ti...", "pt-BR": "Explique por que este limite é importante para você..."},
    
    # Detail keys
    "detail.action_followup": {"es": "Seguimiento", "pt-BR": "Acompanhamento"},
    "detail.action_practice": {"es": "Practicar", "pt-BR": "Praticar"},
    "detail.action_scripts": {"es": "Guiones", "pt-BR": "Scripts"},
    "detail.actions_header": {"es": "Acciones", "pt-BR": "Ações"},
    "detail.not_found_description": {"es": "No se encontró el detalle solicitado", "pt-BR": "O detalhe solicitado não foi encontrado"},
    "detail.not_found_title": {"es": "No encontrado", "pt-BR": "Não encontrado"},
    "detail.practice_count": {"es": "Número de prácticas", "pt-BR": "Número de práticas"},
    "detail.progress_header": {"es": "Progreso", "pt-BR": "Progresso"},
    "detail.statement_header": {"es": "Declaración", "pt-BR": "Declaração"},
    "detail.status": {"es": "Estado", "pt-BR": "Status"},
    "detail.title": {"es": "Detalle", "pt-BR": "Detalhe"},
    "detail.why_matters_header": {"es": "Por qué importa", "pt-BR": "Por que importa"},
    
    # Difficulty keys
    "difficulty.component.completion": {"es": "Finalización", "pt-BR": "Conclusão"},
    "difficulty.component.mood": {"es": "Ánimo", "pt-BR": "Humor"},
    "difficulty.component.sleep": {"es": "Sueño", "pt-BR": "Sono"},
    "difficulty.component.streak": {"es": "Racha", "pt-BR": "Sequência"},
    "difficulty.error.cache": {"es": "Error de caché", "pt-BR": "Erro de cache"},
    "difficulty.error.calculation": {"es": "Error de cálculo", "pt-BR": "Erro de cálculo"},
    "difficulty.error.invalid": {"es": "Valor inválido", "pt-BR": "Valor inválido"},
    "difficulty.error.network": {"es": "Error de red", "pt-BR": "Erro de rede"},
    "difficulty.error.override": {"es": "Error de anulación", "pt-BR": "Erro de substituição"},
    "difficulty.override.challenge": {"es": "Desafío", "pt-BR": "Desafio"},
    "difficulty.override.normal": {"es": "Normal", "pt-BR": "Normal"},
    "difficulty.override.rest": {"es": "Descanso", "pt-BR": "Descanso"},
    
    # Status keys
    "status.adjusted": {"es": "Ajustado", "pt-BR": "Ajustado"},
    "status.archived": {"es": "Archivado", "pt-BR": "Arquivado"},
    "status.draft": {"es": "Borrador", "pt-BR": "Rascunho"},
    "status.practiced": {"es": "Practicado", "pt-BR": "Praticado"},
    "status.ready": {"es": "Listo", "pt-BR": "Pronto"},
    "status.set": {"es": "Establecido", "pt-BR": "Definido"},
    
    # Practice keys
    "practice.context_header": {"es": "Contexto", "pt-BR": "Contexto"},
    "practice.history_count %lld": {"es": "%lld en historial", "pt-BR": "%lld no histórico"},
    "practice.history_header": {"es": "Historial", "pt-BR": "Histórico"},
    "practice.history_ready_badge": {"es": "Listo", "pt-BR": "Pronto"},
    "practice.option_free_description": {"es": "Practica por tu cuenta sin guía", "pt-BR": "Pratique por conta própria sem guia"},
    "practice.option_free_title": {"es": "Práctica libre", "pt-BR": "Prática livre"},
    "practice.option_guided_description": {"es": "Sigue una práctica guiada paso a paso", "pt-BR": "Siga uma prática guiada passo a passo"},
    "practice.option_guided_title": {"es": "Práctica guiada", "pt-BR": "Prática guiada"},
    "practice.option_roleplay_description": {"es": "Practica con escenarios de juego de roles", "pt-BR": "Pratique com cenários de simulação"},
    "practice.option_roleplay_title": {"es": "Juego de roles", "pt-BR": "Simulação"},
    "practice.options_header": {"es": "Opciones", "pt-BR": "Opções"},
    "practice.recommended_badge": {"es": "Recomendado", "pt-BR": "Recomendado"},
    "practice.tip_body_language": {"es": "Presta atención al lenguaje corporal", "pt-BR": "Preste atenção à linguagem corporal"},
    "practice.tip_repetition": {"es": "La repetición ayuda a desarrollar confianza", "pt-BR": "A repetição ajuda a desenvolver confiança"},
    "practice.tip_self_compassion": {"es": "Sé amable contigo mismo durante la práctica", "pt-BR": "Seja gentil consigo mesmo durante a prática"},
    "practice.tip_start_simple": {"es": "Comienza con escenarios simples", "pt-BR": "Comece com cenários simples"},
    "practice.tips_header": {"es": "Consejos", "pt-BR": "Dicas"},
    "practice.title": {"es": "Práctica", "pt-BR": "Prática"},
    
    # Priority matrix keys
    "priority_matrix.currently_met": {"es": "Actualmente satisfecho", "pt-BR": "Atualmente atendido"},
    "priority_matrix.gap_score %lld": {"es": "Puntuación de brecha: %lld", "pt-BR": "Pontuação de lacuna: %lld"},
    "priority_matrix.identified_needs_header": {"es": "Necesidades identificadas", "pt-BR": "Necessidades identificadas"},
    "priority_matrix.importance": {"es": "Importancia", "pt-BR": "Importância"},
    "priority_matrix.navigation_title": {"es": "Matriz de prioridades", "pt-BR": "Matriz de prioridades"},
    "priority_matrix.next_step_define": {"es": "Definir", "pt-BR": "Definir"},
    "priority_matrix.next_step_define_description": {"es": "Define tus límites claramente", "pt-BR": "Defina seus limites claramente"},
    "priority_matrix.next_step_practice": {"es": "Practicar", "pt-BR": "Praticar"},
    "priority_matrix.next_step_practice_description": {"es": "Practica establecer límites", "pt-BR": "Pratique estabelecer limites"},
    "priority_matrix.next_step_scripts": {"es": "Guiones", "pt-BR": "Scripts"},
    "priority_matrix.next_step_scripts_description": {"es": "Prepara respuestas para situaciones", "pt-BR": "Prepare respostas para situações"},
    "priority_matrix.next_steps_header": {"es": "Próximos pasos", "pt-BR": "Próximos passos"},
    "priority_matrix.recommendations_header": {"es": "Recomendaciones", "pt-BR": "Recomendações"},
    "priority_matrix.subtitle": {"es": "Evalúa tus prioridades", "pt-BR": "Avalie suas prioridades"},
    "priority_matrix.title": {"es": "Matriz de prioridades", "pt-BR": "Matriz de prioridades"},
    
    # Scripts keys
    "scripts.error_title": {"es": "Error de guiones", "pt-BR": "Erro de scripts"},
    "scripts.generate": {"es": "Generar", "pt-BR": "Gerar"},
    "scripts.generated_count %lld": {"es": "%lld generados", "pt-BR": "%lld gerados"},
    "scripts.generating": {"es": "Generando...", "pt-BR": "Gerando..."},
    "scripts.practice": {"es": "Practicar", "pt-BR": "Praticar"},
    "scripts.practice_prompts_header": {"es": "Indicaciones de práctica", "pt-BR": "Prompts de prática"},
    "scripts.relationship_type_footer": {"es": "Pie de página de tipo de relación", "pt-BR": "Rodapé de tipo de relacionamento"},
    "scripts.relationship_type_header": {"es": "Tipo de relación", "pt-BR": "Tipo de relacionamento"},
    "scripts.relationship_type_label": {"es": "Tipo", "pt-BR": "Tipo"},
    "scripts.title": {"es": "Guiones", "pt-BR": "Scripts"},
    "scripts.variation.assertive": {"es": "Asertivo", "pt-BR": "Assertivo"},
    "scripts.variation.assertive.description": {"es": "Comunicación directa y confiada", "pt-BR": "Comunicação direta e confiante"},
    "scripts.variation.collaborative": {"es": "Colaborativo", "pt-BR": "Colaborativo"},
    "scripts.variation.collaborative.description": {"es": "Enfoque en soluciones mutuas", "pt-BR": "Foco em soluções mútuas"},
    "scripts.variation.direct": {"es": "Directo", "pt-BR": "Direto"},
    "scripts.variation.direct.description": {"es": "Al grano sin rodeos", "pt-BR": "Direto ao ponto sem rodeios"},
    "scripts.variation.gentle": {"es": "Suave", "pt-BR": "Suave"},
    "scripts.variation.gentle.description": {"es": "Comunicación amable y compasiva", "pt-BR": "Comunicação gentil e compassiva"},
    "scripts.variations_footer": {"es": "Pie de página de variaciones", "pt-BR": "Rodapé de variações"},
    "scripts.variations_header": {"es": "Variaciones", "pt-BR": "Variações"},
}

def main():
    # Load xcstrings file
    xcstrings_path = 'apps/ios/MindFriendApp/Resources/Localizable.xcstrings'
    with open(xcstrings_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    strings = data.get('strings', {})
    translated_count = 0
    
    for key, value in strings.items():
        if key in TRANSLATIONS:
            localizations = value.get('localizations', {})
            trans = TRANSLATIONS[key]
            
            if 'es' in trans:
                if 'es' not in localizations:
                    localizations['es'] = {}
                localizations['es']['stringUnit'] = {
                    'state': 'translated',
                    'value': trans['es']
                }
            
            if 'pt-BR' in trans:
                if 'pt-BR' not in localizations:
                    localizations['pt-BR'] = {}
                localizations['pt-BR']['stringUnit'] = {
                    'state': 'translated',
                    'value': trans['pt-BR']
                }
            
            value['localizations'] = localizations
            translated_count += 1
    
    # Save updated file
    with open(xcstrings_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Applied {translated_count} additional translations")
    
    # Count remaining missing
    missing_count = 0
    for key, value in strings.items():
        localizations = value.get('localizations', {})
        es_loc = localizations.get('es', {})
        es_unit = es_loc.get('stringUnit', {})
        if not es_unit.get('value'):
            missing_count += 1
    
    print(f"Still missing: {missing_count} strings")

if __name__ == '__main__':
    main()
